<span style="color: white; font-weight: bold; font-size: 50px;">Récuperation de la liste des DGEFP</span>

In [2]:
import requests

dataset_id = "liste-publique-des-of-v2"
export_url = f"https://dgefp.opendatasoft.com/api/v2/catalog/datasets/{dataset_id}/exports/csv"
params = {
    "delimiter": ";",  
    "list_separator": ",", 
    "quote_all": "false", 
    "with_bom": "true" 
}

response = requests.get(export_url, params=params)

if response.status_code == 200:
    csv_path = 'donnee.csv'
    with open(csv_path, 'wb') as file:
        file.write(response.content)
    print(f"Les enregistrements ont été exportés et sauvegardés dans '{csv_path}'.")
else:
    print(f"Erreur lors de l'exportation : {response.status_code}")

Les enregistrements ont été exportés et sauvegardés dans 'donnee.csv'.

In [3]:
import pandas as pd

csv_path = 'donnee.csv'

try:
    df = pd.read_csv(csv_path, delimiter=';')
    print(df.head())
    print(f"Nombre total d'enregistrements exportés : {df.shape[0]}")
    print(f"Nombre total de colonnes : {df.shape[1]}")
except FileNotFoundError:
    print(f"Le fichier '{csv_path}' n'existe pas.")
except Exception as e:
    print(f"Une erreur s'est produite : {e}")

C:\Users\PC\AppData\Local\Temp\ipykernel_8212\1650541180.py:6: DtypeWarning: Columns (0,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path, delimiter=';')

  numerodeclarationactivite numerosdeclarationactiviteprecedent  \
0               11788457578                         11788457578
1               11756782875             11930571893,11756782875
2               11922694992                         11922694992
3               93061133106                         93061133106
4               93050103005                         93050103005

       denomination      siren  siretetablissementdeclarant  \
0         01 AFFORP  890176654               89017665400014
1       01 CONTROLE  335060307               33506030700063
2     01 CQFD AUDIT  894612175               89461217500014
3            01MARS  801880683               80188068300025
4  05 VERIFICATIONS  821646213               82164621300024

              adressephysiqueorganismeformation_voie  \
0                                                NaN
1                            106 AV PHILIPPE AUGUSTE
2                               33  RUE ANNA JACQUIN
3                            84  RUE MARECHAL JOFFRE
4  RUE BELLE AUREILLE N F107 BAT FERME BELLE AURE...

   adressephysiqueorganismeformation_codepostal  \
0                                           NaN
1                                       75011.0
2                                       92100.0
3                                        6000.0
4                                        5000.0

  adressephysiqueorganismeformation_ville  \
0                                     NaN
1                                PARIS 11
2                    BOULOGNE BILLANCOURT
3                                    NICE
4                                     GAP

   adressephysiqueorganismeformation_coderegion         geocodageban  ...  \
0                                            11                  NaN  ...
1                                            11  48.856517, 2.391101  ...
2                                            11  48.844944, 2.228016  ...
3                                            93  43.697144, 7.257563  ...
4                                            93  44.535381, 6.052914  ...

     epci_code                                       epci_name dep_code  \
0          NaN                                             NaN      NaN
1  200054781.0                        Métropole du Grand Paris       75
2  200054781.0                        Métropole du Grand Paris       92
3  200030195.0                      Métropole Nice Côte d'Azur       06
4  200067825.0  Communauté d'agglomération Gap-Tallard-Durance       05

            dep_name                    reg_name reg_code  \
0  Pas de départment               Île-de-France       11
1              Paris               Île-de-France       11
2     Hauts-de-Seine               Île-de-France       11
3    Alpes-Maritimes  Provence-Alpes-Côte d'Azur       93
4       Hautes-Alpes  Provence-Alpes-Côte d'Azur       93

                                  toutes_specialites  \
0                               Formations générales
1  Electricité, électronique (non compris automat...
2                              Comptabilité, gestion
3      Spécialités plurivalentes de la communication
4  Electricité, électronique (non compris automat...

  organisme_formation_geocode                               certifications  \
0                       False  Actions de formations,Bilans de compétences
1                        True                        Actions de formations
2                        True                                          NaN
3                        True                                          NaN
4                        True                        Actions de formations

   random_id
0  55.237376
1  76.772237
2  48.627538
3  58.714957
4  28.334234

[5 rows x 43 columns]
Nombre total d'enregistrements exportés : 140989
Nombre total de colonnes : 43

In [4]:
df.to_csv("listes DGFPs.csv", index=False)
df

,numerodeclarationactivite,numerosdeclarationactiviteprecedent,denomination,siren,siretetablissementdeclarant,adressephysiqueorganismeformation_voie,adressephysiqueorganismeformation_codepostal,adressephysiqueorganismeformation_ville,adressephysiqueorganismeformation_coderegion,geocodageban,...,epci_code,epci_name,dep_code,dep_name,reg_name,reg_code,toutes_specialites,organisme_formation_geocode,certifications,random_id
0,11788457578,11788457578,01 AFFORP,890176654,89017665400014,NaN,NaN,NaN,11,NaN,...,NaN,NaN,NaN,Pas de départment,Île-de-France,11,Formations générales,False,"Actions de formations,Bilans de compétences",55.237376
1,11756782875,"11930571893,11756782875",01 CONTROLE,335060307,33506030700063,106 AV PHILIPPE AUGUSTE,75011.0,PARIS 11,11,"48.856517, 2.391101",...,200054781.0,Métropole du Grand Paris,75,Paris,Île-de-France,11,"Electricité, électronique (non compris automat...",True,Actions de formations,76.772237
2,11922694992,11922694992,01 CQFD AUDIT,894612175,89461217500014,33 RUE ANNA JACQUIN,92100.0,BOULOGNE BILLANCOURT,11,"48.844944, 2.228016",...,200054781.0,Métropole du Grand Paris,92,Hauts-de-Seine,Île-de-France,11,"Comptabilité, gestion",True,NaN,48.627538
3,93061133106,93061133106,01MARS,801880683,80188068300025,84 RUE MARECHAL JOFFRE,6000.0,NICE,93,"43.697144, 7.257563",...,200030195.0,Métropole Nice Côte d'Azur,06,Alpes-Maritimes,Provence-Alpes-Côte d'Azur,93,Spécialités plurivalentes de la communication,True,NaN,58.714957
4,93050103005,93050103005,05 VERIFICATIONS,821646213,82164621300024,RUE BELLE AUREILLE N F107 BAT FERME BELLE AURE...,5000.0,GAP,93,"44.535381, 6.052914",...,200067825.0,Communauté d'agglomération Gap-Tallard-Durance,05,Hautes-Alpes,Provence-Alpes-Côte d'Azur,93,"Electricité, électronique (non compris automat...",True,Actions de formations,28.334234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140984,28760673976,"75331298733,28760673976",ZVENIGOROSKY IRENE,832033559,83203355900036,140 ALLÉE DES BUISSONS,76160.0,PREAUX,28,"49.487453, 1.215396",...,200070449.0,Communauté de communes Inter-Caux-Vexin,76,Seine-Maritime,Normandie,28,Santé,True,NaN,54.821904
140985,52490291549,52490291549,ZW FRANCE,531876670,53187667000013,NaN,NaN,NaN,52,NaN,...,NaN,NaN,NaN,Pas de départment,Pays de la Loire,52,"Formations générales,Informatique, traitement ...",False,Actions de formations,66.183582
140986,41570304557,"11930118993,41570304557",ZWICKROELL,315547927,31554792700063,4 Rue Royal Canadian Air Force CS 45191,57075.0,ARS LAQUENEXY,44,NaN,...,NaN,NaN,NaN,Pas de départment,Grand Est,44,"Métallurgie (y compris sidérurgie, fonderie, n...",False,NaN,61.652859
140987,11788581278,11788581278,ZYBRA,878152065,87815206500016,3 CHE DES CARRIERES,78540.0,VERNOUILLET,11,"48.967265, 1.985073",...,200059889.0,Communauté urbaine Grand Paris Seine et Oise,78,Yvelines,Île-de-France,11,"Enseignement, formation",True,NaN,57.888565
140988,11755090675,11755090675,Z. YOUAKIM,539019943,53901994300031,NaN,NaN,NaN,11,NaN,...,NaN,NaN,NaN,Pas de départment,Île-de-France,11,Développement des capacités comportementales e...,False,NaN,76.476018

In [5]:
import pandas as pd

fichier_entree = "listes DGFPs.csv" 

df = pd.read_csv(fichier_entree)

df = df.fillna('')

df.to_csv("listes DGFP.csv", index=False)

df

C:\Users\PC\AppData\Local\Temp\ipykernel_8212\2380296399.py:5: DtypeWarning: Columns (0,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fichier_entree)

,numerodeclarationactivite,numerosdeclarationactiviteprecedent,denomination,siren,siretetablissementdeclarant,adressephysiqueorganismeformation_voie,adressephysiqueorganismeformation_codepostal,adressephysiqueorganismeformation_ville,adressephysiqueorganismeformation_coderegion,geocodageban,...,epci_code,epci_name,dep_code,dep_name,reg_name,reg_code,toutes_specialites,organisme_formation_geocode,certifications,random_id
0,11788457578,11788457578,01 AFFORP,890176654,89017665400014,,,,11,,...,,,,Pas de départment,Île-de-France,11,Formations générales,False,"Actions de formations,Bilans de compétences",55.237376
1,11756782875,"11930571893,11756782875",01 CONTROLE,335060307,33506030700063,106 AV PHILIPPE AUGUSTE,75011.0,PARIS 11,11,"48.856517, 2.391101",...,200054781.0,Métropole du Grand Paris,75,Paris,Île-de-France,11,"Electricité, électronique (non compris automat...",True,Actions de formations,76.772237
2,11922694992,11922694992,01 CQFD AUDIT,894612175,89461217500014,33 RUE ANNA JACQUIN,92100.0,BOULOGNE BILLANCOURT,11,"48.844944, 2.228016",...,200054781.0,Métropole du Grand Paris,92,Hauts-de-Seine,Île-de-France,11,"Comptabilité, gestion",True,,48.627538
3,93061133106,93061133106,01MARS,801880683,80188068300025,84 RUE MARECHAL JOFFRE,6000.0,NICE,93,"43.697144, 7.257563",...,200030195.0,Métropole Nice Côte d'Azur,06,Alpes-Maritimes,Provence-Alpes-Côte d'Azur,93,Spécialités plurivalentes de la communication,True,,58.714957
4,93050103005,93050103005,05 VERIFICATIONS,821646213,82164621300024,RUE BELLE AUREILLE N F107 BAT FERME BELLE AURE...,5000.0,GAP,93,"44.535381, 6.052914",...,200067825.0,Communauté d'agglomération Gap-Tallard-Durance,05,Hautes-Alpes,Provence-Alpes-Côte d'Azur,93,"Electricité, électronique (non compris automat...",True,Actions de formations,28.334234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140984,28760673976,"75331298733,28760673976",ZVENIGOROSKY IRENE,832033559,83203355900036,140 ALLÉE DES BUISSONS,76160.0,PREAUX,28,"49.487453, 1.215396",...,200070449.0,Communauté de communes Inter-Caux-Vexin,76,Seine-Maritime,Normandie,28,Santé,True,,54.821904
140985,52490291549,52490291549,ZW FRANCE,531876670,53187667000013,,,,52,,...,,,,Pas de départment,Pays de la Loire,52,"Formations générales,Informatique, traitement ...",False,Actions de formations,66.183582
140986,41570304557,"11930118993,41570304557",ZWICKROELL,315547927,31554792700063,4 Rue Royal Canadian Air Force CS 45191,57075.0,ARS LAQUENEXY,44,,...,,,,Pas de départment,Grand Est,44,"Métallurgie (y compris sidérurgie, fonderie, n...",False,,61.652859
140987,11788581278,11788581278,ZYBRA,878152065,87815206500016,3 CHE DES CARRIERES,78540.0,VERNOUILLET,11,"48.967265, 1.985073",...,200059889.0,Communauté urbaine Grand Paris Seine et Oise,78,Yvelines,Île-de-France,11,"Enseignement, formation",True,,57.888565
140988,11755090675,11755090675,Z. YOUAKIM,539019943,53901994300031,,,,11,,...,,,,Pas de départment,Île-de-France,11,Développement des capacités comportementales e...,False,,76.476018

<span style="color: white; font-weight: bold; font-size: 50px;">Récuperation des qualiopi DGEFP.</span>

In [6]:
import pandas as pd

df = pd.read_csv("listes DGFP.csv", encoding='utf-8', low_memory=False)

colonnes_qualiopi = [
    'certifications_actionsdeformation',
    'certifications_bilansdecompetences',
    'certifications_vae',
]


df_qualiopi = df[df[colonnes_qualiopi].any(axis=1)]

colonnes_a_conserver = [
    'numerodeclarationactivite',
    'numerosdeclarationactiviteprecedent',
    'denomination', 'siren', 'siretetablissementdeclarant',
    'adressephysiqueorganismeformation_voie',
    'adressephysiqueorganismeformation_codepostal',
    'adressephysiqueorganismeformation_ville',
    'adressephysiqueorganismeformation_coderegion',
    'informationsdeclarees_specialitesdeformation_libellespecialite1',
    'informationsdeclarees_specialitesdeformation_libellespecialite2',
    'informationsdeclarees_specialitesdeformation_libellespecialite3',
    'informationsdeclarees_nbstagiaires',
    'informationsdeclarees_effectifformateurs',
    'informationsdeclarees_nbstagiairesconfiesparunautreof',
    'certifications_actionsdeformation',
    'certifications_bilansdecompetences',
    'certifications_vae',
    'certifications_actionsdeformationparapprentissage'
]

df_qualiopi = df_qualiopi[colonnes_a_conserver]

df_qualiopi.to_csv("Liste_organismes_Qualiopi.csv", index=False, encoding='utf-8')

df_qualiopi

,numerodeclarationactivite,numerosdeclarationactiviteprecedent,denomination,siren,siretetablissementdeclarant,adressephysiqueorganismeformation_voie,adressephysiqueorganismeformation_codepostal,adressephysiqueorganismeformation_ville,adressephysiqueorganismeformation_coderegion,informationsdeclarees_specialitesdeformation_libellespecialite1,informationsdeclarees_specialitesdeformation_libellespecialite2,informationsdeclarees_specialitesdeformation_libellespecialite3,informationsdeclarees_nbstagiaires,informationsdeclarees_effectifformateurs,informationsdeclarees_nbstagiairesconfiesparunautreof,certifications_actionsdeformation,certifications_bilansdecompetences,certifications_vae,certifications_actionsdeformationparapprentissage
0,11788457578,11788457578,01 AFFORP,890176654,89017665400014,NaN,NaN,NaN,11,Formations générales,NaN,NaN,53,4,0,True,True,False,False
1,11756782875,"11930571893,11756782875",01 CONTROLE,335060307,33506030700063,106 AV PHILIPPE AUGUSTE,75011.0,PARIS 11,11,"Electricité, électronique (non compris automat...","Informatique, traitement de l'information, rés...","Nettoyage, assainissement, protection de l'env...",487,4,64,True,False,False,False
4,93050103005,93050103005,05 VERIFICATIONS,821646213,82164621300024,RUE BELLE AUREILLE N F107 BAT FERME BELLE AURE...,5000.0,GAP,93,"Electricité, électronique (non compris automat...","Sécurité des biens et des personnes, police, s...",Autres...,0,0,0,True,False,False,False
10,27210423521,27210423521,1000 BORNES,853070209,85307020900020,27 RUE DE LA LIBERTE,21500.0,MONTBARD,27,"Enseignement, formation",NaN,NaN,72,1,0,True,False,False,False
13,75331062433,75331062433,1001 METIERS,822360988,82236098800015,NaN,NaN,NaN,75,"Développement des capacités d'orientation, d'i...",NaN,NaN,64,3,0,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140977,11922745892,"11922570892,11922745892",ZUCCHETTI FRANCE,512151218,51215121800041,5 PROMENADE DE LA BONNETTE ZAC DES BAR BANNIERS,92230.0,GENNEVILLIERS,11,"Informatique, traitement de l'information, rés...",NaN,NaN,0,0,0,True,False,False,False
140980,11910223091,11910223091,ZUKEN SA,315028126,31502812600037,NaN,NaN,NaN,11,Autres...,NaN,NaN,265,14,0,True,False,False,False
140981,11756929975,"11756929975,11756536575",ZUMA PARIS,791352339,79135233900034,40 BOULEVARD GOUVION-SAINT-CYR,75017.0,PARIS 17,11,Spécialités plurivalentes de la communication,NaN,NaN,0,0,0,True,False,False,False
140982,11941152294,"11941152294,11940261694",ZUND FRANCE,380435917,38043591700014,14 RUE DES FLANDRES,94400.0,VITRY SUR SEINE,11,Technologies industrielles fondamentales,NaN,NaN,339,13,52,True,False,False,False
140985,52490291549,52490291549,ZW FRANCE,531876670,53187667000013,NaN,NaN,NaN,52,Formations générales,"Informatique, traitement de l'information, rés...",NaN,204,5,0,True,False,False,False

In [7]:
import pandas as pd


file_path = "Liste_organismes_Qualiopi.csv"
df = pd.read_csv(file_path)

df["Statut"] = "Qualiopi"

colonnes_ordre = [
    "numerodeclarationactivite",
    "numerosdeclarationactiviteprecedent",
    "denomination", "siren", "siretetablissementdeclarant",
    "Statut",
    "certifications_actionsdeformation",
    "certifications_bilansdecompetences",
    "certifications_vae",
    "certifications_actionsdeformationparapprentissage",
    "adressephysiqueorganismeformation_voie",
    "adressephysiqueorganismeformation_codepostal",
    "adressephysiqueorganismeformation_ville",
    "adressephysiqueorganismeformation_coderegion",
    "informationsdeclarees_specialitesdeformation_libellespecialite1",
    "informationsdeclarees_specialitesdeformation_libellespecialite2",
    "informationsdeclarees_specialitesdeformation_libellespecialite3",
    "informationsdeclarees_nbstagiaires",
    "informationsdeclarees_effectifformateurs",
    "informationsdeclarees_nbstagiairesconfiesparunautreof",

]

df = df[colonnes_ordre]

df.to_csv("Liste_qualiopi_DGEFP_updated_add_row_statut.csv", index=False)
df

,numerodeclarationactivite,numerosdeclarationactiviteprecedent,denomination,siren,siretetablissementdeclarant,Statut,certifications_actionsdeformation,certifications_bilansdecompetences,certifications_vae,certifications_actionsdeformationparapprentissage,adressephysiqueorganismeformation_voie,adressephysiqueorganismeformation_codepostal,adressephysiqueorganismeformation_ville,adressephysiqueorganismeformation_coderegion,informationsdeclarees_specialitesdeformation_libellespecialite1,informationsdeclarees_specialitesdeformation_libellespecialite2,informationsdeclarees_specialitesdeformation_libellespecialite3,informationsdeclarees_nbstagiaires,informationsdeclarees_effectifformateurs,informationsdeclarees_nbstagiairesconfiesparunautreof
0,11788457578,11788457578,01 AFFORP,890176654,89017665400014,Qualiopi,True,True,False,False,NaN,NaN,NaN,11,Formations générales,NaN,NaN,53,4,0
1,11756782875,"11930571893,11756782875",01 CONTROLE,335060307,33506030700063,Qualiopi,True,False,False,False,106 AV PHILIPPE AUGUSTE,75011.0,PARIS 11,11,"Electricité, électronique (non compris automat...","Informatique, traitement de l'information, rés...","Nettoyage, assainissement, protection de l'env...",487,4,64
2,93050103005,93050103005,05 VERIFICATIONS,821646213,82164621300024,Qualiopi,True,False,False,False,RUE BELLE AUREILLE N F107 BAT FERME BELLE AURE...,5000.0,GAP,93,"Electricité, électronique (non compris automat...","Sécurité des biens et des personnes, police, s...",Autres...,0,0,0
3,27210423521,27210423521,1000 BORNES,853070209,85307020900020,Qualiopi,True,False,False,False,27 RUE DE LA LIBERTE,21500.0,MONTBARD,27,"Enseignement, formation",NaN,NaN,72,1,0
4,75331062433,75331062433,1001 METIERS,822360988,82236098800015,Qualiopi,False,True,False,False,NaN,NaN,NaN,75,"Développement des capacités d'orientation, d'i...",NaN,NaN,64,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43276,11922745892,"11922570892,11922745892",ZUCCHETTI FRANCE,512151218,51215121800041,Qualiopi,True,False,False,False,5 PROMENADE DE LA BONNETTE ZAC DES BAR BANNIERS,92230.0,GENNEVILLIERS,11,"Informatique, traitement de l'information, rés...",NaN,NaN,0,0,0
43277,11910223091,11910223091,ZUKEN SA,315028126,31502812600037,Qualiopi,True,False,False,False,NaN,NaN,NaN,11,Autres...,NaN,NaN,265,14,0
43278,11756929975,"11756929975,11756536575",ZUMA PARIS,791352339,79135233900034,Qualiopi,True,False,False,False,40 BOULEVARD GOUVION-SAINT-CYR,75017.0,PARIS 17,11,Spécialités plurivalentes de la communication,NaN,NaN,0,0,0
43279,11941152294,"11941152294,11940261694",ZUND FRANCE,380435917,38043591700014,Qualiopi,True,False,False,False,14 RUE DES FLANDRES,94400.0,VITRY SUR SEINE,11,Technologies industrielles fondamentales,NaN,NaN,339,13,52
43280,52490291549,52490291549,ZW FRANCE,531876670,53187667000013,Qualiopi,True,False,False,False,NaN,NaN,NaN,52,Formations générales,"Informatique, traitement de l'information, rés...",NaN,204,5,0

<span style="color: white; font-weight: bold; font-size: 50px;">Récuperation des non qualiopi DGEFP.</span>

In [8]:
import pandas as pd

df = pd.read_csv("listes DGFP.csv", encoding='utf-8', low_memory=False)

colonnes_qualiopi = [
    'certifications_actionsdeformation',
    'certifications_bilansdecompetences',
    'certifications_vae',
    'certifications_actionsdeformationparapprentissage'
]

df_non_qualiopi = df[df[colonnes_qualiopi].isna().all(axis=1)]

colonnes_a_conserver = [
    'numerodeclarationactivite',
    'numerosdeclarationactiviteprecedent',
    'denomination', 'siren', 'siretetablissementdeclarant',
    'adressephysiqueorganismeformation_voie',
    'adressephysiqueorganismeformation_codepostal',
    'adressephysiqueorganismeformation_ville',
    'adressephysiqueorganismeformation_coderegion',
    'informationsdeclarees_specialitesdeformation_libellespecialite1',
    'informationsdeclarees_specialitesdeformation_libellespecialite2',
    'informationsdeclarees_specialitesdeformation_libellespecialite3',
    'informationsdeclarees_nbstagiaires',
    'informationsdeclarees_effectifformateurs',
    'informationsdeclarees_nbstagiairesconfiesparunautreof',
    'certifications_actionsdeformation',
    'certifications_bilansdecompetences',
    'certifications_vae',
    'certifications_actionsdeformationparapprentissage'
]

df_non_qualiopi = df_non_qualiopi[colonnes_a_conserver]

df_non_qualiopi.to_csv("Liste_non_Qualiopi.csv", index=False, encoding='utf-8')

df_non_qualiopi

,numerodeclarationactivite,numerosdeclarationactiviteprecedent,denomination,siren,siretetablissementdeclarant,adressephysiqueorganismeformation_voie,adressephysiqueorganismeformation_codepostal,adressephysiqueorganismeformation_ville,adressephysiqueorganismeformation_coderegion,informationsdeclarees_specialitesdeformation_libellespecialite1,informationsdeclarees_specialitesdeformation_libellespecialite2,informationsdeclarees_specialitesdeformation_libellespecialite3,informationsdeclarees_nbstagiaires,informationsdeclarees_effectifformateurs,informationsdeclarees_nbstagiairesconfiesparunautreof,certifications_actionsdeformation,certifications_bilansdecompetences,certifications_vae,certifications_actionsdeformationparapprentissage
2,11922694992,11922694992,01 CQFD AUDIT,894612175,89461217500014,33 RUE ANNA JACQUIN,92100.0,BOULOGNE BILLANCOURT,11,"Comptabilité, gestion",NaN,NaN,0,1,300,NaN,NaN,NaN,NaN
3,93061133106,93061133106,01MARS,801880683,80188068300025,84 RUE MARECHAL JOFFRE,6000.0,NICE,93,Spécialités plurivalentes de la communication,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN
5,32800243480,32800243480,07H01,952975084,95297508400015,6 PLACE D’HEDOUVILLE,80300.0,ALBERT,32,Spécialités plurivalentes des services,Autres...,NaN,0,0,0,NaN,NaN,NaN,NaN
6,98970223197,98970223197,0CEAN INDIEN INFORMATIQUE SARL,384520045,38452004500046,NaN,NaN,NaN,4,Spécialités plurivalentes des échanges et de l...,"Enseignement, formation",NaN,128,2,0,NaN,NaN,NaN,NaN
7,52490410349,52490410349,0FC.TECH,917429516,91742951600029,8 PLACE MONSEIGNEUR RUMEAU,49100.0,ANGERS,52,"Informatique, traitement de l'information, rés...",NaN,NaN,0,1,379,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140983,11753254275,11753254275,ZUNINO NAUDEAU BENEDICTE (CAROBELL FORMATION),400838975,40083897500029,NaN,NaN,NaN,11,Développement des capacités comportementales e...,NaN,NaN,22,1,0,NaN,NaN,NaN,NaN
140984,28760673976,"75331298733,28760673976",ZVENIGOROSKY IRENE,832033559,83203355900036,140 ALLÉE DES BUISSONS,76160.0,PREAUX,28,Santé,NaN,NaN,0,1,298,NaN,NaN,NaN,NaN
140986,41570304557,"11930118993,41570304557",ZWICKROELL,315547927,31554792700063,4 Rue Royal Canadian Air Force CS 45191,57075.0,ARS LAQUENEXY,44,"Métallurgie (y compris sidérurgie, fonderie, n...",NaN,NaN,214,16,0,NaN,NaN,NaN,NaN
140987,11788581278,11788581278,ZYBRA,878152065,87815206500016,3 CHE DES CARRIERES,78540.0,VERNOUILLET,11,"Enseignement, formation",NaN,NaN,39,2,175,NaN,NaN,NaN,NaN
140988,11755090675,11755090675,Z. YOUAKIM,539019943,53901994300031,NaN,NaN,NaN,11,Développement des capacités comportementales e...,NaN,NaN,9,1,0,NaN,NaN,NaN,NaN

In [9]:
import pandas as pd

file_path = "Liste_non_Qualiopi.csv"
df = pd.read_csv(file_path, dtype=str)

df = df.fillna("")

df["Statut"] = "Non Qualiopi"

colonnes_ordre = [
    "numerodeclarationactivite",
    "numerosdeclarationactiviteprecedent",
    "denomination", "siren", "siretetablissementdeclarant",
    "Statut",
    "certifications_actionsdeformation",
    "certifications_bilansdecompetences",
    "certifications_vae",
    "certifications_actionsdeformationparapprentissage",
    "adressephysiqueorganismeformation_voie",
    "adressephysiqueorganismeformation_codepostal",
    "adressephysiqueorganismeformation_ville",
    "adressephysiqueorganismeformation_coderegion",
    "informationsdeclarees_specialitesdeformation_libellespecialite1",
    "informationsdeclarees_specialitesdeformation_libellespecialite2",
    "informationsdeclarees_specialitesdeformation_libellespecialite3",
    "informationsdeclarees_nbstagiaires",
    "informationsdeclarees_effectifformateurs",
    "informationsdeclarees_nbstagiairesconfiesparunautreof",
]

df = df[colonnes_ordre]

df.to_csv("Liste_non_qualiopi_DGEFP_updated_add_row_statut.csv", index=False)
df

,numerodeclarationactivite,numerosdeclarationactiviteprecedent,denomination,siren,siretetablissementdeclarant,Statut,certifications_actionsdeformation,certifications_bilansdecompetences,certifications_vae,certifications_actionsdeformationparapprentissage,adressephysiqueorganismeformation_voie,adressephysiqueorganismeformation_codepostal,adressephysiqueorganismeformation_ville,adressephysiqueorganismeformation_coderegion,informationsdeclarees_specialitesdeformation_libellespecialite1,informationsdeclarees_specialitesdeformation_libellespecialite2,informationsdeclarees_specialitesdeformation_libellespecialite3,informationsdeclarees_nbstagiaires,informationsdeclarees_effectifformateurs,informationsdeclarees_nbstagiairesconfiesparunautreof
0,11922694992,11922694992,01 CQFD AUDIT,894612175,89461217500014,Non Qualiopi,,,,,33 RUE ANNA JACQUIN,92100.0,BOULOGNE BILLANCOURT,11,"Comptabilité, gestion",,,0,1,300
1,93061133106,93061133106,01MARS,801880683,80188068300025,Non Qualiopi,,,,,84 RUE MARECHAL JOFFRE,6000.0,NICE,93,Spécialités plurivalentes de la communication,,,0,0,0
2,32800243480,32800243480,07H01,952975084,95297508400015,Non Qualiopi,,,,,6 PLACE D’HEDOUVILLE,80300.0,ALBERT,32,Spécialités plurivalentes des services,Autres...,,0,0,0
3,98970223197,98970223197,0CEAN INDIEN INFORMATIQUE SARL,384520045,38452004500046,Non Qualiopi,,,,,,,,4,Spécialités plurivalentes des échanges et de l...,"Enseignement, formation",,128,2,0
4,52490410349,52490410349,0FC.TECH,917429516,91742951600029,Non Qualiopi,,,,,8 PLACE MONSEIGNEUR RUMEAU,49100.0,ANGERS,52,"Informatique, traitement de l'information, rés...",,,0,1,379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97424,11753254275,11753254275,ZUNINO NAUDEAU BENEDICTE (CAROBELL FORMATION),400838975,40083897500029,Non Qualiopi,,,,,,,,11,Développement des capacités comportementales e...,,,22,1,0
97425,28760673976,"75331298733,28760673976",ZVENIGOROSKY IRENE,832033559,83203355900036,Non Qualiopi,,,,,140 ALLÉE DES BUISSONS,76160.0,PREAUX,28,Santé,,,0,1,298
97426,41570304557,"11930118993,41570304557",ZWICKROELL,315547927,31554792700063,Non Qualiopi,,,,,4 Rue Royal Canadian Air Force CS 45191,57075.0,ARS LAQUENEXY,44,"Métallurgie (y compris sidérurgie, fonderie, n...",,,214,16,0
97427,11788581278,11788581278,ZYBRA,878152065,87815206500016,Non Qualiopi,,,,,3 CHE DES CARRIERES,78540.0,VERNOUILLET,11,"Enseignement, formation",,,39,2,175
97428,11755090675,11755090675,Z. YOUAKIM,539019943,53901994300031,Non Qualiopi,,,,,,,,11,Développement des capacités comportementales e...,,,9,1,0

<span style="color: white; font-weight: bold; font-size: 50px;">Récuperation de la liste des entreprises - Bitrix 24(YAV)</span>

In [10]:
import time
import configparser
import requests
import pandas as pd

def CrmBitrix(content='', params=[], result='', pause_duration=60, max_retries=3, batch_limit=30000):
    config = configparser.ConfigParser()
    config.read('Config.ini')

    if 'BITRIX' not in config:
        raise ValueError('Section BITRIX manquante dans le fichier \'config.ini\'')

    BITRIX_DOMAIN = config.get('BITRIX', 'BITRIX_DOMAIN')
    BITRIX_TOKEN = config.get('BITRIX', 'BITRIX_TOKEN')

    if not BITRIX_DOMAIN or not BITRIX_TOKEN:
        raise ValueError('Domaine et/ou token Bitrix manquants dans le fichier \'config.ini\'')

    params_str = '&'.join(params)
    BitrixUrl = f'https://{BITRIX_DOMAIN}/rest/1/{BITRIX_TOKEN}/{content}?{params_str}&start='

    listId, listTITLE, listEmails, listNumeros, listDATE_CREATE = [], [], [], [], []
    listActivite1, listActivite2, listActivite3 = [], [], []
    listAdresse, listCodePostale, listVille, listSiret, listidd, listphones = [], [], [], [], [], []

    start = 0
    total_records = 0

    while True:
        url = BitrixUrl + str(start)
        
        for attempt in range(max_retries):
            try:
                response = requests.get(url)
                response.raise_for_status()
                break  
            except requests.exceptions.HTTPError as e:
                if response.status_code == 429:
                    wait_time = pause_duration * (2 ** attempt)
                    print(f'Rate limit exceeded. Retrying in {wait_time} seconds...')
                    time.sleep(wait_time)
                else:
                    raise ValueError(f'Erreur lors de la récupération depuis Bitrix : {e}')
            except requests.exceptions.RequestException as e:
                raise ValueError(f'Erreur lors de la récupération depuis Bitrix : {e}')

        data = response.json()

        if 'result' in data:
            contacts = data['result']
            for contact in contacts:
                listId.append(contact.get('ID', ''))
                listTITLE.append(contact.get('TITLE', ''))
                listEmails.append(contact.get('EMAIL', [{}])[0].get('VALUE', ''))
                listNumeros.append(contact.get('PHONE', [{}])[0].get('VALUE', ''))
                listphones.append(contact.get('UF_CRM_1741080141', ''))
                listDATE_CREATE.append(contact.get('DATE_CREATE', ''))
                listActivite1.append(contact.get('UF_CRM_1686295056', ''))
                listActivite2.append(contact.get('UF_CRM_1686295079', ''))
                listActivite3.append(contact.get('UF_CRM_1686295100', ''))
                listAdresse.append(contact.get('UF_CRM_1686295131', ''))
                listCodePostale.append(contact.get('UF_CRM_1686295169', ''))
                listVille.append(contact.get('UF_CRM_1686295194', ''))
                listSiret.append(contact.get('UF_CRM_1686295022', ''))
                listidd.append(contact.get('UF_CRM_1722346888', ''))
                

            total_records += len(contacts) 

            if total_records >= batch_limit:
                print(f"Atteint {batch_limit} enregistrements, pause de 5 minutes...")
                time.sleep(300) 
                total_records = 0 

        if 'next' in data:
            start = data['next']
        else:
            break

    df_btx = pd.DataFrame({
        'ID': listId,
        'CompanyId': listId,
        'nom': listTITLE,
        "Email": listEmails,
        "Crée": listDATE_CREATE,
        "Mobile": listNumeros,
        "Phones": listphones,
        "Activite1": listActivite1,
        "Activite2": listActivite2,
        "Activite3": listActivite3,
        "Adresse": listAdresse,
        "CodePostale": listCodePostale,
        "Ville": listVille,
        "Siret": listSiret,
        "IDS": listidd
    })

    return df_btx

dfb = CrmBitrix(
    content='crm.company.list.json',
    params=[
        'select[]=ID',
        'select[]=TITLE',
        'select[]=EMAIL',
        'select[]=PHONE',
        'select[]=UF_CRM_1741080141',
        'select[]=DATE_CREATE',
        'select[]=UF_CRM_1686295056',
        'select[]=UF_CRM_1686295079',
        'select[]=UF_CRM_1686295100',
        'select[]=UF_CRM_1686295131',
        'select[]=UF_CRM_1686295169',
        'select[]=UF_CRM_1686295194', 
        'select[]=UF_CRM_1686295022',
        'select[]=UF_CRM_1722346888',
    ],
    result="title"
)
dfb

Atteint 30000 enregistrements, pause de 5 minutes...
Atteint 30000 enregistrements, pause de 5 minutes...
Atteint 30000 enregistrements, pause de 5 minutes...

,ID,CompanyId,nom,Email,Crée,Mobile,Phones,Activite1,Activite2,Activite3,Adresse,CodePostale,Ville,Siret,IDS
0,4,4,0CEAN INDIEN INFORMATIQUE SARL,contact@0ceanindienifnormatioque.cfr,2023-06-09T10:32:19+03:00,,None,Spécialités plurivalentes des échanges et de l...,"Informatique, traitement de l'information, rés...","Enseignement, formation",None,None,None,38452004500046,140
1,8,8,0'LISTY,,2023-06-09T10:32:19+03:00,,None,Autres...,None,None,16 avenue Nelson Mandela,97227,STE ANNE,88943425400013,140
2,10,10,1000 ET DEUX IDEES,,2023-06-09T10:32:20+03:00,,None,Journalisme et communication,None,None,17 RUE DE BROCELIANDE,35360,BOISGERVILLY,51202144500014,140
3,16,16,1001 TAILLES,,2023-06-09T10:32:20+03:00,,None,"Habillement (y compris mode, couture)",None,None,None,None,None,52815239000019,140
4,18,18,100POUR100COM,,2023-06-09T10:32:20+03:00,,None,None,None,None,None,None,None,84444399400018,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97030,503374,503374,YLLAW PRODUCTIONS,,2025-03-12T15:42:45+03:00,,None,"Techniques de l'image et du son, métiers conne...",None,None,None,None,None,79992104400035,140
97031,503376,503376,YSB FORMATION,,2025-03-12T15:42:46+03:00,,None,"Techniques de l'image et du son, métiers conne...",None,None,15 RUE VICTOR HUGO,95270,NOISY SUR OISE,93363380200014,140
97032,503378,503378,ZANDC,,2025-03-12T15:42:46+03:00,,None,"Commerce, vente",None,None,None,None,None,93213697100011,140
97033,503380,503380,ZBH EURL,,2025-03-12T15:42:46+03:00,,None,Textile,None,None,111 BD SERURIER RDC,75019,PARIS 19,85365253500016,140
97034,503382,503382,ZEBULON,,2025-03-12T15:42:46+03:00,,None,Autres...,None,None,2 RUE LESCOUVE,80000,AMIENS,42485405700058,140

In [11]:
dfb.to_csv("company.csv", index=False)
dfb.drop_duplicates()
dfb

,ID,CompanyId,nom,Email,Crée,Mobile,Phones,Activite1,Activite2,Activite3,Adresse,CodePostale,Ville,Siret,IDS
0,4,4,0CEAN INDIEN INFORMATIQUE SARL,contact@0ceanindienifnormatioque.cfr,2023-06-09T10:32:19+03:00,,None,Spécialités plurivalentes des échanges et de l...,"Informatique, traitement de l'information, rés...","Enseignement, formation",None,None,None,38452004500046,140
1,8,8,0'LISTY,,2023-06-09T10:32:19+03:00,,None,Autres...,None,None,16 avenue Nelson Mandela,97227,STE ANNE,88943425400013,140
2,10,10,1000 ET DEUX IDEES,,2023-06-09T10:32:20+03:00,,None,Journalisme et communication,None,None,17 RUE DE BROCELIANDE,35360,BOISGERVILLY,51202144500014,140
3,16,16,1001 TAILLES,,2023-06-09T10:32:20+03:00,,None,"Habillement (y compris mode, couture)",None,None,None,None,None,52815239000019,140
4,18,18,100POUR100COM,,2023-06-09T10:32:20+03:00,,None,None,None,None,None,None,None,84444399400018,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97030,503374,503374,YLLAW PRODUCTIONS,,2025-03-12T15:42:45+03:00,,None,"Techniques de l'image et du son, métiers conne...",None,None,None,None,None,79992104400035,140
97031,503376,503376,YSB FORMATION,,2025-03-12T15:42:46+03:00,,None,"Techniques de l'image et du son, métiers conne...",None,None,15 RUE VICTOR HUGO,95270,NOISY SUR OISE,93363380200014,140
97032,503378,503378,ZANDC,,2025-03-12T15:42:46+03:00,,None,"Commerce, vente",None,None,None,None,None,93213697100011,140
97033,503380,503380,ZBH EURL,,2025-03-12T15:42:46+03:00,,None,Textile,None,None,111 BD SERURIER RDC,75019,PARIS 19,85365253500016,140
97034,503382,503382,ZEBULON,,2025-03-12T15:42:46+03:00,,None,Autres...,None,None,2 RUE LESCOUVE,80000,AMIENS,42485405700058,140

In [12]:
import pandas as pd
import requests
import configparser
from requests_oauthlib import OAuth1
import json
import gspread
from oauth2client.service_account import ServiceAccountCredentials
defaultCrmProspectListUrl = "http://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.userfield.list?ID="

listUrls = []
listeId = []
listID = []
listValuesource = []
listIDd = []

datas = {}

responses = requests.get(defaultCrmProspectListUrl)
        
def testedv():
    if responses.status_code == 200:
        datas = responses.json()
        companyfield = datas['result'][10]['LIST']

        for source in companyfield:
            listID.append(source['ID'])
            listValuesource.append(source['VALUE'])
           
            

            df_btx = pd.DataFrame(list(zip(listID, listValuesource)),
                              columns = ["IDS",'Statut'])

        return df_btx

ModuleNotFoundError: No module named 'requests_oauthlib'

In [12]:
dfdd = testedv()
dfdd

    IDS                             Statut
0   140                       Pas Qualiopi
1   142                           Qualiopi
2   146                     Qualiopi perdu
3   158                          NRP + SMS
4   160           NRP + Email Personnalisé
5   162                NRP + Message Vocal
6   164                     Contact Obtenu
7   144          Portage via un concurrent
8   166                      Pas intéressé
9   168                              Fermé
10  170  Formation pas activité principale

In [13]:
df_Bitrixyav = dfb.merge(dfdd, how='left')
df_Bitrixyav.drop_duplicates()
df_Bitrixyav.to_csv('companyyavlist.csv', index=False, encoding='utf-8')
df_Bitrixyav

,ID,CompanyId,nom,Email,Crée,Mobile,Phones,Activite1,Activite2,Activite3,Adresse,CodePostale,Ville,Siret,IDS,Statut
0,4,4,0CEAN INDIEN INFORMATIQUE SARL,contact@0ceanindienifnormatioque.cfr,2023-06-09T10:32:19+03:00,,None,Spécialités plurivalentes des échanges et de l...,"Informatique, traitement de l'information, rés...","Enseignement, formation",None,None,None,38452004500046,140,Pas Qualiopi
1,8,8,0'LISTY,,2023-06-09T10:32:19+03:00,,None,Autres...,None,None,16 avenue Nelson Mandela,97227,STE ANNE,88943425400013,140,Pas Qualiopi
2,10,10,1000 ET DEUX IDEES,,2023-06-09T10:32:20+03:00,,None,Journalisme et communication,None,None,17 RUE DE BROCELIANDE,35360,BOISGERVILLY,51202144500014,140,Pas Qualiopi
3,16,16,1001 TAILLES,,2023-06-09T10:32:20+03:00,,None,"Habillement (y compris mode, couture)",None,None,None,None,None,52815239000019,140,Pas Qualiopi
4,18,18,100POUR100COM,,2023-06-09T10:32:20+03:00,,None,None,None,None,None,None,None,84444399400018,140,Pas Qualiopi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97030,503374,503374,YLLAW PRODUCTIONS,,2025-03-12T15:42:45+03:00,,None,"Techniques de l'image et du son, métiers conne...",None,None,None,None,None,79992104400035,140,Pas Qualiopi
97031,503376,503376,YSB FORMATION,,2025-03-12T15:42:46+03:00,,None,"Techniques de l'image et du son, métiers conne...",None,None,15 RUE VICTOR HUGO,95270,NOISY SUR OISE,93363380200014,140,Pas Qualiopi
97032,503378,503378,ZANDC,,2025-03-12T15:42:46+03:00,,None,"Commerce, vente",None,None,None,None,None,93213697100011,140,Pas Qualiopi
97033,503380,503380,ZBH EURL,,2025-03-12T15:42:46+03:00,,None,Textile,None,None,111 BD SERURIER RDC,75019,PARIS 19,85365253500016,140,Pas Qualiopi
97034,503382,503382,ZEBULON,,2025-03-12T15:42:46+03:00,,None,Autres...,None,None,2 RUE LESCOUVE,80000,AMIENS,42485405700058,140,Pas Qualiopi

In [55]:
#import pandas as pd

#yav_df = pd.read_csv('companyyavlist.csv', dtype=str)

#yav_df = yav_df[yav_df["Siret"].isna() | (yav_df["Siret"] == "")]

#yav_df.to_csv('companyyavlist_supp_pas_desiret.csv', index=False, encoding='utf-8')
#yav_df

In [18]:
#import pandas as pd


#yav_df = pd.read_csv('companyyavlist.csv', dtype=str)

# Trouver les SIRET en double
#doublons = yav_df[yav_df.duplicated(subset=['Siret'], keep=False)]

# Enregistrer les doublons dans un fichier
#doublons.to_csv("siret_doublons2.csv", index=False)

#doublons

In [19]:
#import pandas as pd


#yav_df = pd.read_csv('companyyavlist.csv', dtype=str)

# Trouver les SIRET en double
#doublons = yav_df[yav_df.duplicated(subset=['Siret'], keep=False)]

# Trier les doublons pour qu'ils restent proches
#doublons = doublons.sort_values(by="Siret")

# Enregistrer dans un fichier CSV
#doublons.to_csv("siret_doublons_proches.csv", index=False)

#print(f"Fichier 'siret_doublons_proches.csv' créé avec les doublons bien regroupés.")

# Afficher un aperçu
#doublons

In [20]:
#import pandas as pd

# Charger le fichier CSV
#yav_df = pd.read_csv('entreprises_sans_contacts.csv', dtype=str)

# Trouver les SIRET en double
#doublons = yav_df[yav_df.duplicated(subset=['Siret'], keep=False)]

# Trier pour que les doublons soient proches
#doublons = doublons.sort_values(by="Siret")

# Supprimer une seule occurrence par groupe de doublons
#doublons_sans_un = doublons.groupby("Siret").apply(lambda x: x.iloc[1:]).reset_index(drop=True)

# Enregistrer dans un fichier CSV
#doublons_sans_un.to_csv("siret_doublons_moins_un.csv", index=False)

#print(f"Fichier 'siret_doublons_moins_un.csv' créé avec UN doublon supprimé par groupe.")

# Afficher un aperçu
#doublons_sans_un

<span style="color: white; font-weight: bold; font-size: 50px;">Ceux qui existent dans DGEFP et dans yav</span>

In [23]:
import pandas as pd

yav_df = pd.read_csv('companyyavlist.csv', dtype=str) 
dgefp_df = pd.read_csv('Liste_non_qualiopi_DGEFP_updated_add_row_statut.csv', dtype=str)

yav_df.columns = yav_df.columns.str.strip()
dgefp_df.columns = dgefp_df.columns.str.strip()

entreprises_communes = yav_df[yav_df['Siret'].isin(dgefp_df['siretetablissementdeclarant'])]

entreprises_communes.to_csv('entreprises_communes.csv', index=False)

entreprises_communes

,ID,CompanyId,nom,Email,Crée,Mobile,Activite1,Activite2,Activite3,Adresse,CodePostale,Ville,Siret,IDS,Statut
0,4,4,0CEAN INDIEN INFORMATIQUE SARL,contact@0ceanindienifnormatioque.cfr,2023-06-09T10:32:19+03:00,NaN,Spécialités plurivalentes des échanges et de l...,"Informatique, traitement de l'information, rés...","Enseignement, formation",NaN,NaN,NaN,38452004500046,140,Pas Qualiopi
1,8,8,0'LISTY,NaN,2023-06-09T10:32:19+03:00,NaN,Autres...,NaN,NaN,16 avenue Nelson Mandela,97227,STE ANNE,88943425400013,140,Pas Qualiopi
2,10,10,1000 ET DEUX IDEES,NaN,2023-06-09T10:32:20+03:00,NaN,Journalisme et communication,NaN,NaN,17 RUE DE BROCELIANDE,35360,BOISGERVILLY,51202144500014,140,Pas Qualiopi
3,16,16,1001 TAILLES,NaN,2023-06-09T10:32:20+03:00,NaN,"Habillement (y compris mode, couture)",NaN,NaN,NaN,NaN,NaN,52815239000019,140,Pas Qualiopi
4,18,18,100POUR100COM,NaN,2023-06-09T10:32:20+03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84444399400018,140,Pas Qualiopi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97092,502596,502596,Monsieur YASSINE ARKOUB,NaN,2025-03-11T18:49:51+03:00,NaN,"Enseignement, formation",NaN,NaN,1 B RUE DES FRERES BONNEFF,94500,CHAMPIGNY SUR MARNE,90000067000019,140,Pas Qualiopi
97093,502598,502598,Monsieur YOAN LE GLEHUIR,NaN,2025-03-11T18:49:51+03:00,NaN,Santé,NaN,NaN,NaN,NaN,NaN,89818134200038,140,Pas Qualiopi
97094,502600,502600,Monsieur YOANN DEHON,NaN,2025-03-11T18:49:52+03:00,NaN,"Sécurité des biens et des personnes, police, s...",NaN,NaN,17 AVENUE QUESNAY,93190,LIVRY GARGAN,88371183000025,140,Pas Qualiopi
97095,502602,502602,Monsieur YOANN MAZZA,NaN,2025-03-11T18:49:52+03:00,NaN,"Informatique, traitement de l'information, rés...",NaN,NaN,30 RUE BLANCHET APPARTEMENT B31,44400,REZE,90295874300020,140,Pas Qualiopi
97096,502604,502604,Monsieur YOANN POHER,NaN,2025-03-11T18:49:52+03:00,NaN,Autres...,NaN,NaN,NaN,NaN,NaN,84781441500018,140,Pas Qualiopi

<span style="color: white; font-weight: bold; font-size: 50px;">Listes des non qualiopi de DGFEP qui n'existe pas dans Yav</span>

In [24]:
import pandas as pd

file1_path = 'companyyavlist.csv' 
file2_path = 'Liste_non_qualiopi_DGEFP_updated_add_row_statut.csv'

try:

    companyyav_df = pd.read_csv(file1_path, dtype=str)
    all_records_export_df = pd.read_csv(file2_path, dtype=str, delimiter=',', on_bad_lines='skip', low_memory=False)
except pd.errors.ParserError as e:
    print(f"Erreur lors de la lecture des fichiers CSV : {e}")
    exit()
except FileNotFoundError as e:
    print(f"Fichier introuvable : {e}")
    exit()

if 'siretetablissementdeclarant' in all_records_export_df.columns and 'Siret' in companyyav_df.columns:

    companyyav_df['Siret'] = companyyav_df['Siret'].fillna('').astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
    all_records_export_df['siretetablissementdeclarant'] = all_records_export_df['siretetablissementdeclarant'].fillna('').astype(str).str.strip()

    sirets_companyyav = set(companyyav_df['Siret'])
    sirets_non_qualiopi = set(all_records_export_df['siretetablissementdeclarant'])

    sirets_absents = sirets_non_qualiopi - sirets_companyyav

    missing_in_companyyav = all_records_export_df[all_records_export_df['siretetablissementdeclarant'].isin(sirets_absents)]

    print(f"Nombre total de SIRET dans '{file2_path}' : {len(sirets_non_qualiopi)}")
    print(f"Nombre total de SIRET dans '{file1_path}' : {len(sirets_companyyav)}")
    print(f"Nombre de SIRET présents dans '{file2_path}' mais absents de '{file1_path}' : {len(sirets_absents)}")

    missing_in_companyyav.to_csv("SIRET_absents_companyyav.csv", index=False, encoding="utf-8")
    print("Les SIRET absents ont été sauvegardés dans 'SIRET_absents_companyyav.csv'.")
    
else:
    print("Les colonnes 'Siret' ou 'siretetablissementdeclarant' sont introuvables dans les fichiers.")

Nombre total de SIRET dans 'Liste_non_qualiopi_DGEFP_updated_add_row_statut.csv' : 97007
Nombre total de SIRET dans 'companyyavlist.csv' : 97094
Nombre de SIRET présents dans 'Liste_non_qualiopi_DGEFP_updated_add_row_statut.csv' mais absents de 'companyyavlist.csv' : 389
Les SIRET absents ont été sauvegardés dans 'SIRET_absents_companyyav.csv'.

In [25]:
missing_in_companyyav

,numerodeclarationactivite,numerosdeclarationactiviteprecedent,denomination,siren,siretetablissementdeclarant,Statut,certifications_actionsdeformation,certifications_bilansdecompetences,certifications_vae,certifications_actionsdeformationparapprentissage,adressephysiqueorganismeformation_voie,adressephysiqueorganismeformation_codepostal,adressephysiqueorganismeformation_ville,adressephysiqueorganismeformation_coderegion,informationsdeclarees_specialitesdeformation_libellespecialite1,informationsdeclarees_specialitesdeformation_libellespecialite2,informationsdeclarees_specialitesdeformation_libellespecialite3,informationsdeclarees_nbstagiaires,informationsdeclarees_effectifformateurs,informationsdeclarees_nbstagiairesconfiesparunautreof
638,11922868892,11922868892,ACADEMIE DES METIERS DE LA DIPLOMATIE,930112107,93011210700014,Non Qualiopi,NaN,NaN,NaN,NaN,25 AVENUE MARCEAU,92400.0,COURBEVOIE,11,"Droit, sciences politiques",NaN,NaN,0,0,0
961,93061177206,93061177206,ACP CONSULTING,808775472,80877547200018,Non Qualiopi,NaN,NaN,NaN,NaN,12 AVENUE ANGELIQUE BRAQUET LE VERT-VALLON A1,6200.0,NICE,93,"Commerce, vente",NaN,NaN,0,0,0
1221,44510279251,44510279251,ADAPT,953449865,95344986500013,Non Qualiopi,NaN,NaN,NaN,NaN,33 RUE DU NOCHET,51300.0,ST AMAND SUR FION,44,"Musique, arts du spectacle",NaN,NaN,0,0,0
2973,84691636869,84691636869,ALTEO RESSOURCES,819873019,81987301900015,Non Qualiopi,NaN,NaN,NaN,NaN,3 ALLEE DU BOIS D'ARS,69380.0,LISSIEU,84,Développement des capacités comportementales e...,NaN,NaN,0,1,44
4705,75790166579,75790166579,ASP CONSEILS,930426275,93042627500010,Non Qualiopi,NaN,NaN,NaN,NaN,21 LIEU DIT PICHAUD,79100.0,STE VERGE,75,"Ressources humaines, gestion du personnel, ges...",NaN,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96740,11757189275,11757189275,YLLAW PRODUCTIONS,799921044,79992104400035,Non Qualiopi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,"Techniques de l'image et du son, métiers conne...","Animation culturelle, sportive et de loisirs",NaN,0,0,0
96823,11950925195,11950925195,YSB FORMATION,933633802,93363380200014,Non Qualiopi,NaN,NaN,NaN,NaN,15 RUE VICTOR HUGO,95270.0,NOISY SUR OISE,11,"Techniques de l'image et du son, métiers conne...",NaN,NaN,0,0,0
96887,84630622863,84630622863,ZANDC,932136971,93213697100011,Non Qualiopi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84,"Commerce, vente",Autres...,NaN,0,0,0
96905,11756665575,11756665575,ZBH EURL,853652535,85365253500016,Non Qualiopi,NaN,NaN,NaN,NaN,111 BD SERURIER RDC,75019.0,PARIS 19,11,Textile,NaN,NaN,0,0,0
96911,32800256780,32800256780,ZEBULON,424854057,42485405700058,Non Qualiopi,NaN,NaN,NaN,NaN,2 RUE LESCOUVE,80000.0,AMIENS,32,Autres...,NaN,NaN,0,0,0

In [26]:
import pandas as pd

file_path = 'SIRET_absents_companyyav.csv'

dfbn = pd.read_csv(file_path)

colonnes_a_conserver = [
    'numerodeclarationactivite',
    'numerosdeclarationactiviteprecedent',
    'denomination', 'siren', 'siretetablissementdeclarant',
    'adressephysiqueorganismeformation_voie',
    'adressephysiqueorganismeformation_codepostal',
    'adressephysiqueorganismeformation_ville',
    'adressephysiqueorganismeformation_coderegion',
    'informationsdeclarees_specialitesdeformation_libellespecialite1',
    'informationsdeclarees_specialitesdeformation_libellespecialite2',
    'informationsdeclarees_specialitesdeformation_libellespecialite3',
    'informationsdeclarees_nbstagiaires',
    'informationsdeclarees_effectifformateurs',
    'informationsdeclarees_nbstagiairesconfiesparunautreof',
    'certifications_actionsdeformation',
    'certifications_bilansdecompetences',
    'certifications_vae','certifications_actionsdeformationparapprentissage'
]

df_fil = dfbn[colonnes_a_conserver]

df_fil = df_fil.fillna('')

df_fil['adressephysiqueorganismeformation_codepostal'] = df_fil['adressephysiqueorganismeformation_codepostal'].apply(
    lambda x: str(int(float(x))) if x != '' else ''
)

df_fil.to_csv("A_SIRET_absents_companyyav.csv", index=False)
df_fil

,numerodeclarationactivite,numerosdeclarationactiviteprecedent,denomination,siren,siretetablissementdeclarant,adressephysiqueorganismeformation_voie,adressephysiqueorganismeformation_codepostal,adressephysiqueorganismeformation_ville,adressephysiqueorganismeformation_coderegion,informationsdeclarees_specialitesdeformation_libellespecialite1,informationsdeclarees_specialitesdeformation_libellespecialite2,informationsdeclarees_specialitesdeformation_libellespecialite3,informationsdeclarees_nbstagiaires,informationsdeclarees_effectifformateurs,informationsdeclarees_nbstagiairesconfiesparunautreof,certifications_actionsdeformation,certifications_bilansdecompetences,certifications_vae,certifications_actionsdeformationparapprentissage
0,11922868892,11922868892,ACADEMIE DES METIERS DE LA DIPLOMATIE,930112107,93011210700014,25 AVENUE MARCEAU,92400,COURBEVOIE,11,"Droit, sciences politiques",,,0,0,0,,,,
1,93061177206,93061177206,ACP CONSULTING,808775472,80877547200018,12 AVENUE ANGELIQUE BRAQUET LE VERT-VALLON A1,6200,NICE,93,"Commerce, vente",,,0,0,0,,,,
2,44510279251,44510279251,ADAPT,953449865,95344986500013,33 RUE DU NOCHET,51300,ST AMAND SUR FION,44,"Musique, arts du spectacle",,,0,0,0,,,,
3,84691636869,84691636869,ALTEO RESSOURCES,819873019,81987301900015,3 ALLEE DU BOIS D'ARS,69380,LISSIEU,84,Développement des capacités comportementales e...,,,0,1,44,,,,
4,75790166579,75790166579,ASP CONSEILS,930426275,93042627500010,21 LIEU DIT PICHAUD,79100,STE VERGE,75,"Ressources humaines, gestion du personnel, ges...",,,0,0,0,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,11757189275,11757189275,YLLAW PRODUCTIONS,799921044,79992104400035,,,,11,"Techniques de l'image et du son, métiers conne...","Animation culturelle, sportive et de loisirs",,0,0,0,,,,
385,11950925195,11950925195,YSB FORMATION,933633802,93363380200014,15 RUE VICTOR HUGO,95270,NOISY SUR OISE,11,"Techniques de l'image et du son, métiers conne...",,,0,0,0,,,,
386,84630622863,84630622863,ZANDC,932136971,93213697100011,,,,84,"Commerce, vente",Autres...,,0,0,0,,,,
387,11756665575,11756665575,ZBH EURL,853652535,85365253500016,111 BD SERURIER RDC,75019,PARIS 19,11,Textile,,,0,0,0,,,,
388,32800256780,32800256780,ZEBULON,424854057,42485405700058,2 RUE LESCOUVE,80000,AMIENS,32,Autres...,,,0,0,0,,,,

<span style="color: white; font-weight: bold; font-size: 50px;"> Ajout des entreprises Non Qualiopi de la DGFEP manquantes dans notre CRM Bitrix 24(YAV)</span>

In [27]:
import pandas as pd
import requests
import configparser
import time
import numpy as np
import random

def CrmBitrix(content='', params=[], pause_duration=1, max_retries=3):
    """
    Récupère des entreprises déjà présentes dans Bitrix24 pour éviter les doublons.
    """
    print("Début de la récupération des données de Bitrix24...")

    config = configparser.ConfigParser()
    config.read('config.ini')

    if 'BITRIX' not in config:
        raise ValueError("Section BITRIX manquante dans le fichier 'config.ini'")

    BITRIX_DOMAIN = config.get('BITRIX', 'BITRIX_DOMAIN')
    BITRIX_TOKEN = config.get('BITRIX', 'BITRIX_TOKEN')

    if not BITRIX_DOMAIN or not BITRIX_TOKEN:
        raise ValueError("Domaine et/ou token Bitrix manquants dans le fichier 'config.ini'")

    print(f"Utilisation du domaine Bitrix: {BITRIX_DOMAIN}")

    params_str = '&'.join(params)
    BitrixUrl = f'https://{BITRIX_DOMAIN}/rest/1/{BITRIX_TOKEN}/{content}?{params_str}&start='

    listNoms, listIds, listSIRETs = [], [], []

    start = 0
    while True:
        url = BitrixUrl + str(start)
        print(f"Envoi de la requête à l'URL: {url}")

        for attempt in range(max_retries):
            try:
                response = requests.get(url)
                response.raise_for_status()
                break
            except requests.exceptions.HTTPError as e:
                if response.status_code == 429:
                    wait_time = pause_duration * (2 ** attempt)
                    print(f"Limite atteinte. Nouvelle tentative dans {wait_time} secondes...")
                    time.sleep(wait_time)
                else:
                    raise ValueError(f"Erreur Bitrix: {e}")
            except requests.exceptions.RequestException as e:
                raise ValueError(f"Erreur de connexion: {e}")

        data = response.json()
        if 'result' in data:
            contacts = data['result']
            for contact in contacts:
                listNoms.append(contact.get('TITLE', ''))
                listIds.append(contact.get('ID', ''))
                listSIRETs.append(contact.get('UF_CRM_1686295022', ''))

        if 'next' in data:
            start = data['next']
        else:
            break

    df_btx = pd.DataFrame({'ID': listIds, 'nom': listNoms, 'siretetablissementdeclarant': listSIRETs})
    print("Récupération terminée.")
    return df_btx

def get_statut_value(statut):
    statut_mapping = {
        'Pas Qualiopi': '140',
        'Qualiopi': '142',
        'Qualiopi perdu': '146'
    }
    return statut_mapping.get(statut, '140')

def clean_data(data):
    for key, value in data.items():
        if isinstance(value, (float, np.float64)) and (np.isnan(value) or np.isinf(value)):
            data[key] = ""
    return data

def create_bitrix_company(df_local, df_bitrix, batch_size=50, max_retries=5):
    """
    Crée des entreprises dans Bitrix24 en évitant les doublons et en gérant les erreurs.
    """
    print("Début de la création des entreprises dans Bitrix24...")

    config = configparser.ConfigParser()
    config.read('config.ini')

    BITRIX_DOMAIN = config.get('BITRIX', 'BITRIX_DOMAIN')
    BITRIX_TOKEN = config.get('BITRIX', 'BITRIX_TOKEN')

    if not BITRIX_DOMAIN or not BITRIX_TOKEN:
        raise ValueError("Domaine et/ou token Bitrix manquants dans le fichier 'config.ini'")

    total_created = 0 

    for index, row in df_local.iterrows():
        nom = row.get('denomination', '')
        siret = row.get('siretetablissementdeclarant', '')

        if not df_bitrix[df_bitrix['siretetablissementdeclarant'] == siret].empty:
            print(f"L'entreprise {nom} avec SIRET {siret} existe déjà. Ignorée.")
            continue

        company_data = {
            'TITLE': nom,
            'UF_CRM_1686295022': siret,
            'UF_CRM_1686295131': row.get('adressephysiqueorganismeformation_voie', ''),
            'UF_CRM_1686295169': row.get('adressephysiqueorganismeformation_codepostal', ''),
            'UF_CRM_1686295194': row.get('adressephysiqueorganismeformation_ville', ''),
            'UF_CRM_1686295056': row.get('informationsdeclarees_specialitesdeformation_libellespecialite1', ''),
            'UF_CRM_1722346888': get_statut_value(row.get('statut', ''))
        }

        company_data = clean_data(company_data)

        create_url = f'https://{BITRIX_DOMAIN}/rest/1/{BITRIX_TOKEN}/crm.company.add.json'

        for attempt in range(max_retries):
            response = requests.post(create_url, json={'fields': company_data})

            if response.status_code == 200:
                print(f"Entreprise créée avec succès pour {nom}")
                total_created += 1
                break 
            elif response.status_code == 429:
                wait_time = 2 * (2 ** attempt)
                print(f"Trop de requêtes. Réessai dans {wait_time} secondes...")
                time.sleep(wait_time)
            else:
                print(f"Erreur lors de la création de {nom}: {response.text}")
                break 

        if total_created % batch_size == 0 and total_created > 0:
            pause_time = random.uniform(300, 600) 
            print(f"Pause de {pause_time:.2f} secondes après {batch_size} créations...")
            time.sleep(pause_time)

    print("Création des entreprises terminée.")

input_csv = 'A_SIRET_absents_companyyav.csv'
df_local = pd.read_csv(input_csv, low_memory=False)

df_local.fillna({'informationsdeclarees_nbstagiaires': 0, 'informationsdeclarees_effectifformateurs': 0, 'informationsdeclarees_nbstagiairesconfiesparunautreof': 0}, inplace=True)

df_btx = CrmBitrix(content='crm.company.list.json', params=['select[]=ID', 'select[]=TITLE', 'select[]=UF_CRM_1686295022'])

create_bitrix_company(df_local, df_btx, batch_size=50)

print("Script terminé avec succès !")

Début de la récupération des données de Bitrix24...
Utilisation du domaine Bitrix: yav.bitrix24.fr
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=0
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=50
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=100
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=150
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=200
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=250
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=300
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=350
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=400
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=450
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=500
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=550
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=600
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=650
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=700
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=750
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=800
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=850
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=900
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=950
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1000
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1050
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1100
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1150
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1200
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1250
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1300
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1350
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1400
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1450
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1500
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1550
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1600
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1650
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1700
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1750
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1800
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1850
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1900
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=1950
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2000
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2050
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2100
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2150
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2200
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2250
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2300
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2350
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2400
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2450
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2500
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2550
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2600
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2650
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2700
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2750
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2800
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2850
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2900
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=2950
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3000
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3050
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3100
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3150
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3200
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3250
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3300
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3350
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3400
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3450
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3500
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3550
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3600
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3650
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3700
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3750
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3800
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3850
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3900
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=3950
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4000
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4050
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4100
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4150
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4200
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4250
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4300
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4350
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4400
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4450
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4500
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4550
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4600
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4650
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4700
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4750
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4800
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4850
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4900
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=4950
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5000
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5050
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5100
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5150
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5200
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5250
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5300
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5350
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5400
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5450
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5500
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5550
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5600
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5650
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5700
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5750
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5800
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5850
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5900
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=5950
Envoi de la requête à l'URL: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&select[]=UF_CRM_1686295022&start=6000

<span style="color: white; font-weight: bold; font-size: 50px;">Récuperation de la liste des contacts (Yav) </span>

In [28]:
import time
import configparser
import requests
import pandas as pd

def CrmBitrix(content='', params=[], result='', pause_duration=1, max_retries=3):
    config = configparser.ConfigParser()
    config.read('Config.ini')

    if 'BITRIX' not in config:
        raise ValueError('Section BITRIX manquante dans le fichier \'config.ini\'')

    BITRIX_DOMAIN = config.get('BITRIX', 'BITRIX_DOMAIN')
    BITRIX_TOKEN = config.get('BITRIX', 'BITRIX_TOKEN')

    if not BITRIX_DOMAIN or not BITRIX_TOKEN:
        raise ValueError('Domaine et/ou token Bitrix manquants dans le fichier \'config.ini\'')

    params_str = '&'.join(params)
    BitrixUrl = f'https://{BITRIX_DOMAIN}/rest/1/{BITRIX_TOKEN}/{content}?{params_str}&start='
    
    listUrls = []
    listIds = []
    listNom = []
    listCOMPANY_ID = []
    listDATE_CREATE = []
    listEmails = []

    url = BitrixUrl + "0"
    while True:
        try:
            response = requests.get(url)
            response.raise_for_status()
        except requests.exceptions.RequestException as e:
            raise ValueError(f'Erreur lors de la récupération depuis Bitrix : {e}')
        
        data = response.json()
        if 'result' in data:
            contacts = data['result']
            for contact in contacts:
                if result == 'email':
                    if 'EMAIL' in contact:
                        email = contact['EMAIL'][0]['VALUE']
                        listEmails.append(email)
                elif result == 'title': 
                    listNom.append(contact['NAME'])
                    email = contact['EMAIL'][0]['VALUE'] if 'EMAIL' in contact else ''
                    listEmails.append(email)
                    listIds.append(contact['ID'])
                    listDATE_CREATE.append(contact['DATE_CREATE'])
                    listCOMPANY_ID.append(contact['COMPANY_ID'])
                else:
                    return 'Erreur avec les données attendues. Merci de vérifier la variable \'result\'.'

        if 'next' in data:
            url = BitrixUrl + str(data['next'])
        else:
            break

    if result == 'email':
        df_btx = pd.DataFrame({'email': listEmails})
    elif result == 'title':
        df_btx = pd.DataFrame({
            'ID': listIds,
            'Noms': listNom,
            'ID Entreprise': listCOMPANY_ID,
            "Email": listEmails,
            "Date de creation": listDATE_CREATE,
        })
    else:
        return 'Erreur avec les données attendues. Merci de vérifier la variable \'result\'.'

    return df_btx

df_Bitrix_contact2 = CrmBitrix(
    content='crm.contact.list.json',
    params=[
        'select[]=ID',
        'select[]=NAME',
        'select[]=COMPANY_ID',
        'select[]=EMAIL',
        'select[]=DATE_CREATE',
    ],
    result="title"
)

print(df_Bitrix_contact2)

        ID       Noms ID Entreprise                                Email  \
0        2    Jacques             4    jacques@0ceanidieninformatique.fr
1        6   Chrystel        145038  chrystele.binder@1-2-3-possible.com
2       10          .             0                1001tailles@gmail.com
3       12    Michael        155086                 mfuseur@mjbright.net
4       14      Corne             0               contact@artibiocom.com
...    ...        ...           ...                                  ...
1326  3358  stephanie        499720        stephanie.leguiriec@gmail.com
1327  3360    Estelle        500404           estellelaurentcm@gmail.com
1328  3364    Ludovic          None                 acces.line@orange.fr
1329  3366        Ony          None              ony.randriana@gmail.com
1330  3368    Anthony          None            lorion.anthony@hotmail.fr

               Date de creation
0     2023-06-09T10:36:49+03:00
1     2023-06-09T17:42:56+03:00
2     2023-06-09T18:15:53+03:00
3     2023-06-12T10:55:43+03:00
4     2023-06-12T11:10:45+03:00
...                         ...
1326  2025-02-27T18:22:00+03:00
1327  2025-02-27T19:50:40+03:00
1328  2025-03-04T14:27:47+03:00
1329  2025-03-04T14:42:52+03:00
1330  2025-03-11T11:38:31+03:00

[1331 rows x 5 columns]

In [29]:
df_Bitrix_contact2.to_csv('contacts_yav.csv', index=False, encoding='utf-8')
df_Bitrix_contact2

,ID,Noms,ID Entreprise,Email,Date de creation
0,2,Jacques,4,jacques@0ceanidieninformatique.fr,2023-06-09T10:36:49+03:00
1,6,Chrystel,145038,chrystele.binder@1-2-3-possible.com,2023-06-09T17:42:56+03:00
2,10,.,0,1001tailles@gmail.com,2023-06-09T18:15:53+03:00
3,12,Michael,155086,mfuseur@mjbright.net,2023-06-12T10:55:43+03:00
4,14,Corne,0,contact@artibiocom.com,2023-06-12T11:10:45+03:00
...,...,...,...,...,...
1326,3358,stephanie,499720,stephanie.leguiriec@gmail.com,2025-02-27T18:22:00+03:00
1327,3360,Estelle,500404,estellelaurentcm@gmail.com,2025-02-27T19:50:40+03:00
1328,3364,Ludovic,None,acces.line@orange.fr,2025-03-04T14:27:47+03:00
1329,3366,Ony,None,ony.randriana@gmail.com,2025-03-04T14:42:52+03:00
1330,3368,Anthony,None,lorion.anthony@hotmail.fr,2025-03-11T11:38:31+03:00

<span style="color: white; font-weight: bold; font-size: 50px;">Les entreprises qui existent dans Bitrix 24 (YAV) mais pas dans DGEFP</span>

In [30]:
import pandas as pd

yav_df = pd.read_csv('companyyavlist.csv', dtype=str)
dgefp_df = pd.read_csv('listes DGFP.csv', dtype=str)

yav_df.columns = yav_df.columns.str.strip()
dgefp_df.columns = dgefp_df.columns.str.strip()

entreprises_uniques_yav = yav_df[~yav_df['Siret'].isin(dgefp_df['siretetablissementdeclarant'])]

entreprises_uniques_yav.to_csv('entreprises_de_yav_qui_sont_plus_dans_DGEFP.csv', index=False)

entreprises_uniques_yav

,ID,CompanyId,nom,Email,Crée,Mobile,Activite1,Activite2,Activite3,Adresse,CodePostale,Ville,Siret,IDS,Statut
358,1560,1560,ACCES SOLUTIONS,NaN,2023-06-09T10:33:17+03:00,NaN,"Informatique, traitement de l'information, rés...",NaN,NaN,NaN,NaN,NaN,45386774900021,140,Pas Qualiopi
1044,4244,4244,AGILE QUALITE,NaN,2023-06-09T10:35:05+03:00,NaN,"Sécurité des biens et des personnes, police, s...",Autres...,NaN,50 RUE ETTORE BUGATTI,76800,ST ETIENNE DU ROUVRAY,84815251800025,140,Pas Qualiopi
4450,16336,16336,BARRU MURIELLE,NaN,2023-06-09T10:42:16+03:00,NaN,"Productions végétales,cultures spécialisées",NaN,NaN,NaN,NaN,NaN,49411482000066,140,Pas Qualiopi
5559,20168,20168,BRANDIBAS GILLES,NaN,2023-06-09T11:32:40+03:00,NaN,Psychologie,NaN,NaN,NaN,NaN,NaN,43306058900069,140,Pas Qualiopi
6084,21964,21964,CADU ALBAN,NaN,2023-06-09T11:33:49+03:00,NaN,Développement des capacités comportementales e...,NaN,NaN,NaN,NaN,NaN,88432925100026,140,Pas Qualiopi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95654,499720,499720,Stephanie le guierec,stephanie.leguiriec@gmail.com,2025-03-01T12:39:13+03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164,Contact Obtenu
95897,500206,500206,Monsieur HENRI AIT-AZZOUZ,NaN,2025-03-02T17:03:00+03:00,NaN,"Sécurité des biens et des personnes, police, s...",NaN,NaN,CHEMIN DES CHAMPS DE PRUNIERS,4100,MANOSQUE,83519367300026,140,Pas Qualiopi
95996,500404,500404,Estelle Laurent,estellelaurentcm@gmail.com,2025-03-03T11:47:11+03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96494,501400,501400,Madame CHARLOTTE PELE,NaN,2025-03-11T17:20:13+03:00,NaN,Santé,NaN,NaN,NaN,NaN,NaN,88510997500064,140,Pas Qualiopi
96672,501756,501756,Madame OLIVIA PONCHON,NaN,2025-03-11T17:46:09+03:00,NaN,"Commerce, vente",NaN,NaN,NaN,NaN,NaN,88889838400027,140,Pas Qualiopi

<span style="color: white; font-weight: bold; font-size: 50px;">Liste des entreprises fermées (Yav) qui ne sont pas attachées à un contact</span>

In [31]:
import pandas as pd

file1 = "entreprises_de_yav_qui_sont_plus_dans_DGEFP.csv"
file2 = "contacts_yav.csv"

df1 = pd.read_csv(file1, dtype=str, keep_default_na=False) 
df2 = pd.read_csv(file2, dtype=str, keep_default_na=False)

df1["ID"] = df1["ID"].astype(str).str.strip()
df2["ID Entreprise"] = df2["ID Entreprise"].astype(str).str.strip()

entreprises_sans_contact = df1[~df1["ID"].isin(df2["ID Entreprise"])]

print("Liste des entreprises sans contact :")
print(entreprises_sans_contact)

entreprises_sans_contact.to_csv("entreprises_sans_contacts.csv", index=False)
entreprises_sans_contact

Liste des entreprises sans contact :
        ID CompanyId                        nom Email  \
0     1560      1560            ACCES SOLUTIONS
1     4244      4244              AGILE QUALITE
2    16336     16336             BARRU MURIELLE
3    20168     20168           BRANDIBAS GILLES
4    21964     21964                 CADU ALBAN
..     ...       ...                        ...   ...
90  499488    499488       Madame LEILA LAMBLIN
91  499666    499666       Monsieur XAVIER RIBA
93  500206    500206  Monsieur HENRI AIT-AZZOUZ
95  501400    501400      Madame CHARLOTTE PELE
96  501756    501756      Madame OLIVIA PONCHON

                         Crée Mobile  \
0   2023-06-09T10:33:17+03:00
1   2023-06-09T10:35:05+03:00
2   2023-06-09T10:42:16+03:00
3   2023-06-09T11:32:40+03:00
4   2023-06-09T11:33:49+03:00
..                        ...    ...
90  2025-02-27T13:28:44+03:00
91  2025-02-27T13:48:09+03:00
93  2025-03-02T17:03:00+03:00
95  2025-03-11T17:20:13+03:00
96  2025-03-11T17:46:09+03:00

                                            Activite1  Activite2 Activite3  \
0   Informatique, traitement de l'information, rés...
1   Sécurité des biens et des personnes, police, s...  Autres...
2         Productions végétales,cultures spécialisées
3                                         Psychologie
4   Développement des capacités comportementales e...
..                                                ...        ...       ...
90      Spécialités plurivalentes de la communication
91                            Enseignement, formation
93  Sécurité des biens et des personnes, police, s...
95                                              Santé
96                                    Commerce, vente

                          Adresse CodePostale                  Ville  \
0
1           50 RUE ETTORE BUGATTI       76800  ST ETIENNE DU ROUVRAY
2
3
4
..                            ...         ...                    ...
90
91
93  CHEMIN DES CHAMPS DE PRUNIERS        4100               MANOSQUE
95
96

             Siret  IDS        Statut
0   45386774900021  140  Pas Qualiopi
1   84815251800025  140  Pas Qualiopi
2   49411482000066  140  Pas Qualiopi
3   43306058900069  140  Pas Qualiopi
4   88432925100026  140  Pas Qualiopi
..             ...  ...           ...
90  88812922800019  140  Pas Qualiopi
91  90132170300018  140  Pas Qualiopi
93  83519367300026  140  Pas Qualiopi
95  88510997500064  140  Pas Qualiopi
96  88889838400027  140  Pas Qualiopi

[92 rows x 15 columns]

,ID,CompanyId,nom,Email,Crée,Mobile,Activite1,Activite2,Activite3,Adresse,CodePostale,Ville,Siret,IDS,Statut
0,1560,1560,ACCES SOLUTIONS,,2023-06-09T10:33:17+03:00,,"Informatique, traitement de l'information, rés...",,,,,,45386774900021,140,Pas Qualiopi
1,4244,4244,AGILE QUALITE,,2023-06-09T10:35:05+03:00,,"Sécurité des biens et des personnes, police, s...",Autres...,,50 RUE ETTORE BUGATTI,76800,ST ETIENNE DU ROUVRAY,84815251800025,140,Pas Qualiopi
2,16336,16336,BARRU MURIELLE,,2023-06-09T10:42:16+03:00,,"Productions végétales,cultures spécialisées",,,,,,49411482000066,140,Pas Qualiopi
3,20168,20168,BRANDIBAS GILLES,,2023-06-09T11:32:40+03:00,,Psychologie,,,,,,43306058900069,140,Pas Qualiopi
4,21964,21964,CADU ALBAN,,2023-06-09T11:33:49+03:00,,Développement des capacités comportementales e...,,,,,,88432925100026,140,Pas Qualiopi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,499488,499488,Madame LEILA LAMBLIN,,2025-02-27T13:28:44+03:00,,Spécialités plurivalentes de la communication,,,,,,88812922800019,140,Pas Qualiopi
91,499666,499666,Monsieur XAVIER RIBA,,2025-02-27T13:48:09+03:00,,"Enseignement, formation",,,,,,90132170300018,140,Pas Qualiopi
93,500206,500206,Monsieur HENRI AIT-AZZOUZ,,2025-03-02T17:03:00+03:00,,"Sécurité des biens et des personnes, police, s...",,,CHEMIN DES CHAMPS DE PRUNIERS,4100,MANOSQUE,83519367300026,140,Pas Qualiopi
95,501400,501400,Madame CHARLOTTE PELE,,2025-03-11T17:20:13+03:00,,Santé,,,,,,88510997500064,140,Pas Qualiopi
96,501756,501756,Madame OLIVIA PONCHON,,2025-03-11T17:46:09+03:00,,"Commerce, vente",,,,,,88889838400027,140,Pas Qualiopi

In [32]:
import pandas as pd
import requests
import configparser
import time

def CrmBitrix(content='', params=[], result='', pause_duration=600, batch_size=30000, max_retries=5):
    print("Début de la récupération des données de Bitrix24...")

    config = configparser.ConfigParser()
    config.read('config.ini')

    BITRIX_DOMAIN = config.get('BITRIX', 'BITRIX_DOMAIN')
    BITRIX_TOKEN = config.get('BITRIX', 'BITRIX_TOKEN')

    if not BITRIX_DOMAIN or not BITRIX_TOKEN:
        raise ValueError('Domaine et/ou token Bitrix manquants dans config.ini')

    print(f"Connexion à Bitrix24 : {BITRIX_DOMAIN}")

    params_str = '&'.join(params)
    BitrixUrl = f'https://{BITRIX_DOMAIN}/rest/1/{BITRIX_TOKEN}/{content}?{params_str}&start='
    
    listNoms, listIds = [], []
    start = 0
    total_fetched = 0

    while True:
        url = BitrixUrl + str(start)
        print(f"Requête : {url}")

        for attempt in range(max_retries):
            try:
                response = requests.get(url)
                response.raise_for_status()
                break
            except requests.exceptions.HTTPError as e:
                if response.status_code in [429, 503]:  
                    wait_time = pause_duration * (2 ** attempt)  
                    print(f'Erreur {response.status_code}. Pause de {wait_time} secondes...')
                    time.sleep(wait_time)
                else:
                    raise ValueError(f'Erreur HTTP Bitrix : {e}')
            except requests.exceptions.RequestException as e:
                raise ValueError(f'Erreur de connexion Bitrix : {e}')

        data = response.json()
        if 'result' in data:
            contacts = data['result']
            total_fetched += len(contacts)
            print(f"Entreprises récupérées (total) : {total_fetched}")

            for contact in contacts:
                listNoms.append(contact.get('TITLE', ''))
                listIds.append(contact.get('ID', ''))

        if 'next' in data:
            start = data['next']
        else:
            break

        if total_fetched % batch_size == 0:
            print(f"Pause de {pause_duration} secondes après {total_fetched} entrées...")
            time.sleep(pause_duration)

    df_btx = pd.DataFrame({'ID': listIds, 'nom': listNoms})
    print("Récupération Bitrix24 terminée.")
    return df_btx

def delete_bitrix_companies(df_local, df_bitrix, pause_between_requests=1):
    print("Début de la suppression des entreprises dans Bitrix24...")

    config = configparser.ConfigParser()
    config.read('config.ini')

    BITRIX_DOMAIN = config.get('BITRIX', 'BITRIX_DOMAIN')
    BITRIX_TOKEN = config.get('BITRIX', 'BITRIX_TOKEN')

    if not BITRIX_DOMAIN or not BITRIX_TOKEN:
        raise ValueError('Domaine et/ou token Bitrix manquants dans config.ini')

    delete_url = f'https://{BITRIX_DOMAIN}/rest/1/{BITRIX_TOKEN}/crm.company.delete.json'

    df_local['ID'] = df_local['ID'].astype(str)
    df_bitrix['ID'] = df_bitrix['ID'].astype(str)

    ids_to_delete = df_local[df_local['ID'].isin(df_bitrix['ID'])]['ID'].tolist()
    print(f"{len(ids_to_delete)} entreprises trouvées dans Bitrix. Suppression en cours...")

    for idx, company_id in enumerate(ids_to_delete):
        params = {'id': company_id}
        print(f"Suppression de l'entreprise ID {company_id} ({idx + 1}/{len(ids_to_delete)})...")

        for attempt in range(3):  
            try:
                response = requests.post(delete_url, params=params)
                response.raise_for_status()
                print(f"Entreprise ID {company_id} supprimée.")
                break
            except requests.exceptions.HTTPError as e:
                if response.status_code in [429, 503]:
                    wait_time = pause_between_requests * (2 ** attempt)
                    print(f"Erreur {response.status_code}. Attente de {wait_time} secondes avant nouvelle tentative...")
                    time.sleep(wait_time)
                else:
                    print(f"Échec de suppression de ID {company_id}. Réponse: {response.text}")
                    break
            except requests.exceptions.RequestException as e:
                print(f"Erreur réseau lors de la suppression de ID {company_id}: {e}")
                break

        time.sleep(pause_between_requests)  

    print("Suppression des entreprises terminée.")

input_csv = 'entreprises_sans_contacts.csv'
print(" Chargement du fichier CSV local...")
df_local = pd.read_csv(input_csv, dtype=str)
print(f"Nombre total d'entreprises à vérifier : {len(df_local)}")

df_btx = CrmBitrix(
    content='crm.company.list.json',
    params=['select[]=ID', 'select[]=TITLE'],
    result="title"
)

delete_bitrix_companies(df_local, df_btx)

print("Opération terminée !")

 Chargement du fichier CSV local...
Nombre total d'entreprises à vérifier : 92
Début de la récupération des données de Bitrix24...
Connexion à Bitrix24 : yav.bitrix24.fr
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=0
Entreprises récupérées (total) : 50
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=50
Entreprises récupérées (total) : 100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=100
Entreprises récupérées (total) : 150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=150
Entreprises récupérées (total) : 200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=200
Entreprises récupérées (total) : 250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=250
Entreprises récupérées (total) : 300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=300
Entreprises récupérées (total) : 350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=350
Entreprises récupérées (total) : 400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=400
Entreprises récupérées (total) : 450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=450
Entreprises récupérées (total) : 500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=500
Entreprises récupérées (total) : 550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=550
Entreprises récupérées (total) : 600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=600
Entreprises récupérées (total) : 650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=650
Entreprises récupérées (total) : 700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=700
Entreprises récupérées (total) : 750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=750
Entreprises récupérées (total) : 800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=800
Entreprises récupérées (total) : 850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=850
Entreprises récupérées (total) : 900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=900
Entreprises récupérées (total) : 950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=950
Entreprises récupérées (total) : 1000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1000
Entreprises récupérées (total) : 1050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1050
Entreprises récupérées (total) : 1100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1100
Entreprises récupérées (total) : 1150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1150
Entreprises récupérées (total) : 1200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1200
Entreprises récupérées (total) : 1250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1250
Entreprises récupérées (total) : 1300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1300
Entreprises récupérées (total) : 1350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1350
Entreprises récupérées (total) : 1400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1400
Entreprises récupérées (total) : 1450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1450
Entreprises récupérées (total) : 1500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1500
Entreprises récupérées (total) : 1550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1550
Entreprises récupérées (total) : 1600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1600
Entreprises récupérées (total) : 1650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1650
Entreprises récupérées (total) : 1700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1700
Entreprises récupérées (total) : 1750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1750
Entreprises récupérées (total) : 1800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1800
Entreprises récupérées (total) : 1850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1850
Entreprises récupérées (total) : 1900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1900
Entreprises récupérées (total) : 1950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1950
Entreprises récupérées (total) : 2000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2000
Entreprises récupérées (total) : 2050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2050
Entreprises récupérées (total) : 2100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2100
Entreprises récupérées (total) : 2150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2150
Entreprises récupérées (total) : 2200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2200
Entreprises récupérées (total) : 2250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2250
Entreprises récupérées (total) : 2300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2300
Entreprises récupérées (total) : 2350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2350
Entreprises récupérées (total) : 2400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2400
Entreprises récupérées (total) : 2450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2450
Entreprises récupérées (total) : 2500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2500
Entreprises récupérées (total) : 2550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2550
Entreprises récupérées (total) : 2600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2600
Entreprises récupérées (total) : 2650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2650
Entreprises récupérées (total) : 2700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2700
Entreprises récupérées (total) : 2750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2750
Entreprises récupérées (total) : 2800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2800
Entreprises récupérées (total) : 2850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2850
Entreprises récupérées (total) : 2900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2900
Entreprises récupérées (total) : 2950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2950
Entreprises récupérées (total) : 3000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3000
Entreprises récupérées (total) : 3050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3050
Entreprises récupérées (total) : 3100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3100
Entreprises récupérées (total) : 3150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3150
Entreprises récupérées (total) : 3200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3200
Entreprises récupérées (total) : 3250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3250
Entreprises récupérées (total) : 3300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3300
Entreprises récupérées (total) : 3350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3350
Entreprises récupérées (total) : 3400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3400
Entreprises récupérées (total) : 3450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3450
Entreprises récupérées (total) : 3500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3500
Entreprises récupérées (total) : 3550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3550
Entreprises récupérées (total) : 3600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3600
Entreprises récupérées (total) : 3650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3650
Entreprises récupérées (total) : 3700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3700
Entreprises récupérées (total) : 3750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3750
Entreprises récupérées (total) : 3800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3800
Entreprises récupérées (total) : 3850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3850
Entreprises récupérées (total) : 3900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3900
Entreprises récupérées (total) : 3950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3950
Entreprises récupérées (total) : 4000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4000
Entreprises récupérées (total) : 4050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4050
Entreprises récupérées (total) : 4100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4100
Entreprises récupérées (total) : 4150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4150
Entreprises récupérées (total) : 4200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4200
Entreprises récupérées (total) : 4250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4250
Entreprises récupérées (total) : 4300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4300
Entreprises récupérées (total) : 4350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4350
Entreprises récupérées (total) : 4400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4400
Entreprises récupérées (total) : 4450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4450
Entreprises récupérées (total) : 4500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4500
Entreprises récupérées (total) : 4550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4550
Entreprises récupérées (total) : 4600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4600
Entreprises récupérées (total) : 4650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4650
Entreprises récupérées (total) : 4700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4700
Entreprises récupérées (total) : 4750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4750
Entreprises récupérées (total) : 4800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4800
Entreprises récupérées (total) : 4850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4850
Entreprises récupérées (total) : 4900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4900
Entreprises récupérées (total) : 4950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4950
Entreprises récupérées (total) : 5000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5000
Entreprises récupérées (total) : 5050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5050
Entreprises récupérées (total) : 5100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5100
Entreprises récupérées (total) : 5150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5150
Entreprises récupérées (total) : 5200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5200
Entreprises récupérées (total) : 5250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5250
Entreprises récupérées (total) : 5300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5300
Entreprises récupérées (total) : 5350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5350
Entreprises récupérées (total) : 5400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5400
Entreprises récupérées (total) : 5450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5450
Entreprises récupérées (total) : 5500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5500
Entreprises récupérées (total) : 5550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5550
Entreprises récupérées (total) : 5600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5600
Entreprises récupérées (total) : 5650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5650
Entreprises récupérées (total) : 5700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5700
Entreprises récupérées (total) : 5750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5750
Entreprises récupérées (total) : 5800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5800
Entreprises récupérées (total) : 5850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5850
Entreprises récupérées (total) : 5900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5900
Entreprises récupérées (total) : 5950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5950
Entreprises récupérées (total) : 6000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6000
Entreprises récupérées (total) : 6050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6050
Entreprises récupérées (total) : 6100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6100
Entreprises récupérées (total) : 6150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6150
Entreprises récupérées (total) : 6200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6200
Entreprises récupérées (total) : 6250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6250
Entreprises récupérées (total) : 6300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6300
Entreprises récupérées (total) : 6350

<span style="color: white; font-weight: bold; font-size: 50px;">Qualiopi dans la liste yav</span>

In [33]:
import pandas as pd

try:
    yav_df = pd.read_csv('companyyavlist.csv', dtype=str)
    dgefp_df = pd.read_csv('Liste_qualiopi_DGEFP_updated_add_row_statut.csv', dtype=str)
except FileNotFoundError:
    print("Erreur : Un des fichiers CSV est introuvable. Vérifie les noms et l'emplacement.")
    exit()
except Exception as e:
    print(f"Erreur lors du chargement des fichiers : {e}")
    exit()

print("Colonnes de YAV :", list(yav_df.columns))
print("Colonnes de DGEFP :", list(dgefp_df.columns))

col_yav = 'Siret'
col_dgefp = 'siretetablissementdeclarant'

if col_yav in yav_df.columns and col_dgefp in dgefp_df.columns:

    entreprises_communes = yav_df[yav_df[col_yav].isin(dgefp_df[col_dgefp])]
    entreprises_uniques_yav = yav_df[~yav_df[col_yav].isin(dgefp_df[col_dgefp])]
    entreprises_uniques_dgefp = dgefp_df[~dgefp_df[col_dgefp].isin(yav_df[col_yav])]

    entreprises_communes.to_csv('entreprises_dans_DGEFP_et_YAV.csv', index=False)
    entreprises_uniques_yav.to_csv('entreprises_uniques_YAV.csv', index=False)
    entreprises_uniques_dgefp.to_csv('entreprises_uniques_DGEFP.csv', index=False)

    print(f"{entreprises_communes.shape[0]} entreprises trouvées dans les DEUX fichiers et enregistrées dans 'entreprises_dans_DGEFP_et_YAV.csv'.")
    print(f"{entreprises_uniques_yav.shape[0]} entreprises sont UNIQUEMENT dans YAV et enregistrées dans 'entreprises_uniques_YAV.csv'.")
    print(f"{entreprises_uniques_dgefp.shape[0]} entreprises sont UNIQUEMENT dans DGEFP et enregistrées dans 'entreprises_uniques_DGEFP.csv'.")

    print("Exemples de SIRET dans YAV :", yav_df[col_yav].head(10).tolist())
    print("Exemples de SIRET dans DGEFP :", dgefp_df[col_dgefp].head(10).tolist())

    print(f"{entreprises_uniques_yav.shape[0]} entreprises de YAV ne sont PAS reconnues dans DGEFP.")
    print("Exemples de SIRET non trouvés :", entreprises_uniques_yav[col_yav].head(10).tolist())

else:
    print("Erreur : Vérifie les noms des colonnes dans tes fichiers !")

Colonnes de YAV : ['ID', 'CompanyId', 'nom', 'Email', 'Crée', 'Mobile', 'Activite1', 'Activite2', 'Activite3', 'Adresse', 'CodePostale', 'Ville', 'Siret', 'IDS', 'Statut']
Colonnes de DGEFP : ['numerodeclarationactivite', 'numerosdeclarationactiviteprecedent', 'denomination', 'siren', 'siretetablissementdeclarant', 'Statut', 'certifications_actionsdeformation', 'certifications_bilansdecompetences', 'certifications_vae', 'certifications_actionsdeformationparapprentissage', 'adressephysiqueorganismeformation_voie', 'adressephysiqueorganismeformation_codepostal', 'adressephysiqueorganismeformation_ville', 'adressephysiqueorganismeformation_coderegion', 'informationsdeclarees_specialitesdeformation_libellespecialite1', 'informationsdeclarees_specialitesdeformation_libellespecialite2', 'informationsdeclarees_specialitesdeformation_libellespecialite3', 'informationsdeclarees_nbstagiaires', 'informationsdeclarees_effectifformateurs', 'informationsdeclarees_nbstagiairesconfiesparunautreof']
359 entreprises trouvées dans les DEUX fichiers et enregistrées dans 'entreprises_dans_DGEFP_et_YAV.csv'.
96738 entreprises sont UNIQUEMENT dans YAV et enregistrées dans 'entreprises_uniques_YAV.csv'.
42872 entreprises sont UNIQUEMENT dans DGEFP et enregistrées dans 'entreprises_uniques_DGEFP.csv'.
Exemples de SIRET dans YAV : ['38452004500046', '88943425400013', '51202144500014', '52815239000019', '84444399400018', '52339644800038', '45402139500032', '44094825500029', '87991161800038', '49837669800029']
Exemples de SIRET dans DGEFP : ['89017665400014', '33506030700063', '82164621300024', '85307020900020', '82236098800015', '95307856500017', '52502412100044', '88055223700039', '82944823200019', '84995185000015']
96738 entreprises de YAV ne sont PAS reconnues dans DGEFP.
Exemples de SIRET non trouvés : ['38452004500046', '88943425400013', '51202144500014', '52815239000019', '84444399400018', '52339644800038', '45402139500032', '44094825500029', '87991161800038', '49837669800029']

In [34]:
entreprises_communes.to_csv('entreprises_qualio_supp2.csv', index=False)
entreprises_communes

,ID,CompanyId,nom,Email,Crée,Mobile,Activite1,Activite2,Activite3,Adresse,CodePostale,Ville,Siret,IDS,Statut
207,954,954,A.B. CONSEIL,NaN,2023-06-09T10:32:53+03:00,NaN,"Finances, banque, assurances","Ressources humaines, gestion du personnel, ges...",NaN,ZA DU PUECH RADIER BAT 6 ENTREE B PORTE 6A,34970,LATTES,44871553200025,140,Pas Qualiopi
851,3462,3462,A.E.R.A.M AUTO ECOLE DE L'ESPLANADE 3,NaN,2023-06-09T10:34:36+03:00,NaN,"Enseignement, formation",NaN,NaN,NaN,NaN,NaN,83047093600014,140,Pas Qualiopi
1357,5376,5376,ALDS,NaN,2023-06-09T10:35:45+03:00,NaN,Spécialités plurivalentes sanitaires et sociales,Santé,Travail social,25 AVENUE DES AULNES,78250,MEULAN EN YVELINES,33127971100021,142,Qualiopi
3687,13378,13378,ATELIER INSTANT T,NaN,2023-06-09T10:40:32+03:00,NaN,Bâtiment: construction et couverture,"Informatique, traitement de l'information, rés...",NaN,27 BIS RUE MARAT,94200,IVRY SUR SEINE,81344246400018,140,Pas Qualiopi
4166,15336,15336,AVISO DEVELOPPEMENT,NaN,2023-06-09T10:41:43+03:00,NaN,"Enseignement, formation",NaN,NaN,NaN,NaN,NaN,52350407400023,140,Pas Qualiopi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96204,500820,500820,DS BEAUTE FORMATION - DS BEAUTE,NaN,2025-03-11T16:39:07+03:00,NaN,"Coiffure, esthétique et autres spécialités des...",NaN,NaN,NaN,NaN,NaN,85268914000022,140,Pas Qualiopi
96238,500888,500888,EROS,NaN,2025-03-11T16:39:15+03:00,NaN,"Transport, manutention, magasinage",NaN,NaN,37 B RUE DECROMBECQUE,62300,LENS,79425564600042,140,Pas Qualiopi
96280,500972,500972,FUNEFORMATION SAS,NaN,2025-03-11T16:46:39+03:00,NaN,Formations générales,NaN,NaN,350 RUE ARTHUR BRUNET,59220,DENAIN,80492560000012,140,Pas Qualiopi
96557,501526,501526,Madame FLORENCE RIGE,NaN,2025-03-11T17:32:20+03:00,NaN,"Agro-alimentaire, alimentation, cuisine",NaN,NaN,NaN,NaN,NaN,43960746600042,140,Pas Qualiopi
96775,501962,501962,MOBY,NaN,2025-03-11T18:01:40+03:00,NaN,"Informatique, traitement de l'information, rés...",NaN,NaN,NaN,NaN,NaN,75180845200013,140,Pas Qualiopi

In [35]:
import pandas as pd
import requests
import configparser
import time

def CrmBitrix(content='', params=[], result='', pause_duration=60, batch_size=30000, max_retries=5):
    print("Début de la récupération des données de Bitrix24...")

    config = configparser.ConfigParser()
    config.read('config.ini')

    BITRIX_DOMAIN = config.get('BITRIX', 'BITRIX_DOMAIN')
    BITRIX_TOKEN = config.get('BITRIX', 'BITRIX_TOKEN')

    if not BITRIX_DOMAIN or not BITRIX_TOKEN:
        raise ValueError('Domaine et/ou token Bitrix manquants dans config.ini')

    print(f"Connexion à Bitrix24 : {BITRIX_DOMAIN}")

    params_str = '&'.join(params)
    BitrixUrl = f'https://{BITRIX_DOMAIN}/rest/1/{BITRIX_TOKEN}/{content}?{params_str}&start='
    
    listNoms, listIds = [], []
    start = 0
    total_fetched = 0

    while True:
        url = BitrixUrl + str(start)
        print(f"Requête : {url}")

        for attempt in range(max_retries):
            try:
                response = requests.get(url)
                response.raise_for_status()
                break
            except requests.exceptions.HTTPError as e:
                if response.status_code in [429, 503]:  
                    wait_time = pause_duration * (2 ** attempt)  
                    print(f'Erreur {response.status_code}. Pause de {wait_time} secondes...')
                    time.sleep(wait_time)
                else:
                    raise ValueError(f'Erreur HTTP Bitrix : {e}')
            except requests.exceptions.RequestException as e:
                raise ValueError(f'Erreur de connexion Bitrix : {e}')

        data = response.json()
        if 'result' in data:
            contacts = data['result']
            total_fetched += len(contacts)
            print(f"Entreprises récupérées (total) : {total_fetched}")

            for contact in contacts:
                listNoms.append(contact.get('TITLE', ''))
                listIds.append(contact.get('ID', ''))

        if 'next' in data:
            start = data['next']
        else:
            break

        if total_fetched % batch_size == 0:
            print(f"Pause de {pause_duration} secondes après {total_fetched} entrées...")
            time.sleep(pause_duration)

    df_btx = pd.DataFrame({'ID': listIds, 'nom': listNoms})
    print("Récupération Bitrix24 terminée.")
    return df_btx

def delete_bitrix_companies(df_local, df_bitrix, pause_between_requests=1):
    print("Début de la suppression des entreprises dans Bitrix24...")

    config = configparser.ConfigParser()
    config.read('config.ini')

    BITRIX_DOMAIN = config.get('BITRIX', 'BITRIX_DOMAIN')
    BITRIX_TOKEN = config.get('BITRIX', 'BITRIX_TOKEN')

    if not BITRIX_DOMAIN or not BITRIX_TOKEN:
        raise ValueError('Domaine et/ou token Bitrix manquants dans config.ini')

    delete_url = f'https://{BITRIX_DOMAIN}/rest/1/{BITRIX_TOKEN}/crm.company.delete.json'

    df_local['ID'] = df_local['ID'].astype(str)
    df_bitrix['ID'] = df_bitrix['ID'].astype(str)

    ids_to_delete = df_local[df_local['ID'].isin(df_bitrix['ID'])]['ID'].tolist()
    print(f"{len(ids_to_delete)} entreprises trouvées dans Bitrix. Suppression en cours...")

    for idx, company_id in enumerate(ids_to_delete):
        params = {'id': company_id}
        print(f"Suppression de l'entreprise ID {company_id} ({idx + 1}/{len(ids_to_delete)})...")

        for attempt in range(3):  
            try:
                response = requests.post(delete_url, params=params)
                response.raise_for_status()
                print(f"Entreprise ID {company_id} supprimée.")
                break
            except requests.exceptions.HTTPError as e:
                if response.status_code in [429, 503]:
                    wait_time = pause_between_requests * (2 ** attempt)
                    print(f"Erreur {response.status_code}. Attente de {wait_time} secondes avant nouvelle tentative...")
                    time.sleep(wait_time)
                else:
                    print(f"Échec de suppression de ID {company_id}. Réponse: {response.text}")
                    break
            except requests.exceptions.RequestException as e:
                print(f"Erreur réseau lors de la suppression de ID {company_id}: {e}")
                break

        time.sleep(pause_between_requests)  

    print("Suppression des entreprises terminée.")

input_csv = 'entreprises_qualio_supp2.csv'
print(" Chargement du fichier CSV local...")
df_local = pd.read_csv(input_csv, dtype=str)
print(f"Nombre total d'entreprises à vérifier : {len(df_local)}")

df_btx = CrmBitrix(
    content='crm.company.list.json',
    params=['select[]=ID', 'select[]=TITLE'],
    result="title"
)

delete_bitrix_companies(df_local, df_btx)

print("Opération terminée !")

 Chargement du fichier CSV local...
Nombre total d'entreprises à vérifier : 359
Début de la récupération des données de Bitrix24...
Connexion à Bitrix24 : yav.bitrix24.fr
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=0
Entreprises récupérées (total) : 50
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=50
Entreprises récupérées (total) : 100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=100
Entreprises récupérées (total) : 150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=150
Entreprises récupérées (total) : 200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=200
Entreprises récupérées (total) : 250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=250
Entreprises récupérées (total) : 300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=300
Entreprises récupérées (total) : 350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=350
Entreprises récupérées (total) : 400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=400
Entreprises récupérées (total) : 450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=450
Entreprises récupérées (total) : 500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=500
Entreprises récupérées (total) : 550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=550
Entreprises récupérées (total) : 600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=600
Entreprises récupérées (total) : 650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=650
Entreprises récupérées (total) : 700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=700
Entreprises récupérées (total) : 750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=750
Entreprises récupérées (total) : 800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=800
Entreprises récupérées (total) : 850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=850
Entreprises récupérées (total) : 900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=900
Entreprises récupérées (total) : 950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=950
Entreprises récupérées (total) : 1000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1000
Entreprises récupérées (total) : 1050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1050
Entreprises récupérées (total) : 1100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1100
Entreprises récupérées (total) : 1150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1150
Entreprises récupérées (total) : 1200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1200
Entreprises récupérées (total) : 1250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1250
Entreprises récupérées (total) : 1300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1300
Entreprises récupérées (total) : 1350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1350
Entreprises récupérées (total) : 1400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1400
Entreprises récupérées (total) : 1450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1450
Entreprises récupérées (total) : 1500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1500
Entreprises récupérées (total) : 1550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1550
Entreprises récupérées (total) : 1600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1600
Entreprises récupérées (total) : 1650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1650
Entreprises récupérées (total) : 1700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1700
Entreprises récupérées (total) : 1750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1750
Entreprises récupérées (total) : 1800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1800
Entreprises récupérées (total) : 1850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1850
Entreprises récupérées (total) : 1900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1900
Entreprises récupérées (total) : 1950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=1950
Entreprises récupérées (total) : 2000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2000
Entreprises récupérées (total) : 2050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2050
Entreprises récupérées (total) : 2100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2100
Entreprises récupérées (total) : 2150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2150
Entreprises récupérées (total) : 2200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2200
Entreprises récupérées (total) : 2250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2250
Entreprises récupérées (total) : 2300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2300
Entreprises récupérées (total) : 2350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2350
Entreprises récupérées (total) : 2400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2400
Entreprises récupérées (total) : 2450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2450
Entreprises récupérées (total) : 2500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2500
Entreprises récupérées (total) : 2550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2550
Entreprises récupérées (total) : 2600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2600
Entreprises récupérées (total) : 2650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2650
Entreprises récupérées (total) : 2700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2700
Entreprises récupérées (total) : 2750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2750
Entreprises récupérées (total) : 2800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2800
Entreprises récupérées (total) : 2850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2850
Entreprises récupérées (total) : 2900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2900
Entreprises récupérées (total) : 2950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=2950
Entreprises récupérées (total) : 3000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3000
Entreprises récupérées (total) : 3050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3050
Entreprises récupérées (total) : 3100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3100
Entreprises récupérées (total) : 3150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3150
Entreprises récupérées (total) : 3200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3200
Entreprises récupérées (total) : 3250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3250
Entreprises récupérées (total) : 3300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3300
Entreprises récupérées (total) : 3350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3350
Entreprises récupérées (total) : 3400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3400
Entreprises récupérées (total) : 3450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3450
Entreprises récupérées (total) : 3500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3500
Entreprises récupérées (total) : 3550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3550
Entreprises récupérées (total) : 3600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3600
Entreprises récupérées (total) : 3650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3650
Entreprises récupérées (total) : 3700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3700
Entreprises récupérées (total) : 3750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3750
Entreprises récupérées (total) : 3800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3800
Entreprises récupérées (total) : 3850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3850
Entreprises récupérées (total) : 3900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3900
Entreprises récupérées (total) : 3950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=3950
Entreprises récupérées (total) : 4000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4000
Entreprises récupérées (total) : 4050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4050
Entreprises récupérées (total) : 4100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4100
Entreprises récupérées (total) : 4150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4150
Entreprises récupérées (total) : 4200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4200
Entreprises récupérées (total) : 4250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4250
Entreprises récupérées (total) : 4300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4300
Entreprises récupérées (total) : 4350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4350
Entreprises récupérées (total) : 4400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4400
Entreprises récupérées (total) : 4450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4450
Entreprises récupérées (total) : 4500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4500
Entreprises récupérées (total) : 4550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4550
Entreprises récupérées (total) : 4600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4600
Entreprises récupérées (total) : 4650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4650
Entreprises récupérées (total) : 4700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4700
Entreprises récupérées (total) : 4750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4750
Entreprises récupérées (total) : 4800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4800
Entreprises récupérées (total) : 4850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4850
Entreprises récupérées (total) : 4900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4900
Entreprises récupérées (total) : 4950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=4950
Entreprises récupérées (total) : 5000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5000
Entreprises récupérées (total) : 5050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5050
Entreprises récupérées (total) : 5100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5100
Entreprises récupérées (total) : 5150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5150
Entreprises récupérées (total) : 5200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5200
Entreprises récupérées (total) : 5250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5250
Entreprises récupérées (total) : 5300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5300
Entreprises récupérées (total) : 5350
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5350
Entreprises récupérées (total) : 5400
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5400
Entreprises récupérées (total) : 5450
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5450
Entreprises récupérées (total) : 5500
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5500
Entreprises récupérées (total) : 5550
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5550
Entreprises récupérées (total) : 5600
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5600
Entreprises récupérées (total) : 5650
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5650
Entreprises récupérées (total) : 5700
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5700
Entreprises récupérées (total) : 5750
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5750
Entreprises récupérées (total) : 5800
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5800
Entreprises récupérées (total) : 5850
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5850
Entreprises récupérées (total) : 5900
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5900
Entreprises récupérées (total) : 5950
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=5950
Entreprises récupérées (total) : 6000
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6000
Entreprises récupérées (total) : 6050
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6050
Entreprises récupérées (total) : 6100
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6100
Entreprises récupérées (total) : 6150
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6150
Entreprises récupérées (total) : 6200
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6200
Entreprises récupérées (total) : 6250
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6250
Entreprises récupérées (total) : 6300
Requête : https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select[]=ID&select[]=TITLE&start=6300
Entreprises récupérées (total) : 6350

<span style="color: white; font-weight: bold; font-size: 50px;">Base-email</span>m

<span style="color: white; font-weight: bold; font-size: 50px;">Historiques</span>

In [ ]:
import gspread
import pandas as pd
from datetime import datetime

gc = gspread.service_account(filename="qualiopiperdv2.json")

sh = gc.open_by_key('1lw16MgBwEpj8MocT8CBRfgJB-sDwX834EB3zkxMEEz8')

reference_sheet_name = "Dernière_MAJ(DGEFP)"

colonnes_a_conserver = [
    'denomination', 'siretetablissementdeclarant',
    'certifications_actionsdeformation',
    'certifications_bilansdecompetences',
    'certifications_vae',
    'adressephysiqueorganismeformation_voie',
    'adressephysiqueorganismeformation_ville',
    'adressephysiqueorganismeformation_codepostal',
    'adressephysiqueorganismeformation_coderegion',
    'informationsdeclarees_specialitesdeformation_libellespecialite1',
    'informationsdeclarees_specialitesdeformation_libellespecialite2',
    'informationsdeclarees_specialitesdeformation_libellespecialite3',
    'informationsdeclarees_nbstagiaires',
    'informationsdeclarees_effectifformateurs',
    'informationsdeclarees_nbstagiairesconfiesparunautreof',
]

df = pd.read_csv('listes DGFPs.csv', usecols=colonnes_a_conserver, dtype=str)

df = df.fillna('')

df['Statut'] = df.apply(
    lambda row: "Qualiopi" if 'True' in [row['certifications_actionsdeformation'], 
                                         row['certifications_bilansdecompetences'], 
                                         row['certifications_vae']] else "Non Qualiopi", 
    axis=1
)

rows = [df.columns.tolist()] + df.values.tolist()

try:
    reference_worksheet = sh.worksheet(reference_sheet_name)
    old_data = pd.DataFrame(reference_worksheet.get_all_records())
    first_execution = False
except gspread.exceptions.WorksheetNotFound:
    print("Première exécution : sauvegarde des données actuelles sans comparaison.")
    first_execution = True
    old_data = pd.DataFrame()

if first_execution:
    reference_worksheet = sh.add_worksheet(title=reference_sheet_name, rows=len(rows), cols=len(df.columns))
    reference_worksheet.update(rows)
    print("Données initiales enregistrées avec statut.")
else:

    old_sirets = set(old_data["siretetablissementdeclarant"])
    new_sirets = set(df["siretetablissementdeclarant"])

    removed_sirets = old_sirets - new_sirets
    removed_entries = old_data[old_data["siretetablissementdeclarant"].isin(removed_sirets)]
    removed_entries["Statut"] = "Fermé"

    added_sirets = new_sirets - old_sirets
    added_entries = df[df["siretetablissementdeclarant"].isin(added_sirets)]

    merged_data = old_data.merge(df, on="siretetablissementdeclarant", suffixes=('_old', '_new'))
    modified_entries = merged_data[merged_data["Statut_old"] != merged_data["Statut_new"]]

    if not added_entries.empty or not removed_entries.empty or not modified_entries.empty:
        now = datetime.now()
        sheet_name = now.strftime("Historique_%d-%m-%Y_%Hh%M")
        worksheet = sh.add_worksheet(title=sheet_name, rows=len(rows), cols=len(df.columns))

        worksheet.update(rows)

        sh.del_worksheet(reference_worksheet)
        reference_worksheet = sh.add_worksheet(title=reference_sheet_name, rows=len(rows), cols=len(df.columns))
        reference_worksheet.update(rows)

        print(f"Changement détecté : feuille '{sheet_name}' créée.")
    else:
        print("Aucun changement détecté, pas de nouvelle feuille créée.")

In [14]:
import pandas as pd

fichier = "Copie de ORGANISME DE FORMATION.csv"

df = pd.read_csv(fichier, delimiter=",", dtype={"SIRET": str}).fillna("")

df["SIRET"] = df["SIRET"].apply(lambda x: f"{int(float(x)) :014d}" if pd.notnull(x) and x.replace(".", "").isdigit() else x)

print(df["SIRET"].head())

fichier_sortie = "ORGANISME_DE_FORMATION_CLEAN.csv"
df.to_csv(fichier_sortie, index=False)

df

C:\Users\PC\AppData\Local\Temp\ipykernel_17080\2106445813.py:5: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fichier, delimiter=",", dtype={"SIRET": str}).fillna("")

0    42417608900102
1    51117706500022
2    82853477600020
3
4
Name: SIRET, dtype: object

,NOM.,Unnamed: 1,ADRESSE,CODE POSTAL,VILLE,TELEPHONE,ADRESSE E-MAIL,FORME_JURIDIQUE,DIRIGEANT,IMMATRICULATION,ANNEE_CA,CA,RESULTAT,EFFECTIF,NAF APE,SIRET,EFFECTIF_MIN,EFFECTIF_MAX,Qualiopi ?
0,301,,801 AVENUE CHAMPS BLANCS,35510,CESSON SEVIGNE,02 44 10 13 50,contact@formaouest.fr,Societe par actions simplifiee a associe unique,MVGROUP (personne morale),8 septembre 1999,2019.0,28 605 140 €,344 763 €,,6311Z,42417608900102,,,Oui
1,981,,129 AVENUE GENEVE,74000,ANNECY,06 08 75 22 43,nicolas@pluceo.fr,Société à responsabilité limitée à associé unique,BOUVIER FRANCOIS,23 mars 2009,2021.0,,,,8559A,51117706500022,,,Oui
2,'PISTE SECURITE',,41 RUE MOLIERE,92120,MONTROUGE,06 60 11 81 90,contact@piste-securite.com,,ALI DAMIR,,,,,,7490B,82853477600020,,,Oui
3,'PISTE SECURITE',,41 RUE MOLIERE,92120,MONTROUGE,06 60 11 81 90,damir.ali@piste-securite.com,,,,,,,,,,,,Oui
4,& CO,,67 RUE EOLE,14370,CHICHEBOVILLE,02 31 23 30 00,ouine@wanadoo.fr,,,,,,,,,,,,Oui
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38680,ZORBA FORMATION CONCEPT,,7 SQUARE JULES VERNE,56890,ST AVE,06 30 64 14 09,pierre.cougoulic@wanadoo.fr,,,,,,,,,,,,Oui
38681,ZUILI A,,147 AVENUE MONT VENTOUX,84450,JONQUERETTES,04 90 85 09 17,anais.zuili@sophrologie-relationnelle.fr,,,,,,,,8559B,32944822900057,1.0,2.0,Oui
38682,ZUILI A,,147 AVENUE MONT VENTOUX,84450,JONQUERETTES,04 90 85 09 17,anais@sophrozuili.com,Societe par actions simplifiee,,26 juillet 2016,2020.0,,,,8559A,82167328200017,,,Oui
38683,ZULLO JOSE,,9 RUE VAVIN,75006,PARIS,06 88 62 49 42,concrescoconseil@gmail.com,,,,,,,,8560Z,40162302000039,,,Oui
38684,ZULLO JOSE,,9 RUE VAVIN,75006,PARIS,06 88 62 49 42,jzullo@solocal.com,,,,,,,,8560Z,40162302000039,,,Oui

<span style="color: white; font-weight: bold; font-size: 50px;">Entreprises Fermées Base-email.com (Les entreprises qu'on a acheté</span>

In [15]:
import pandas as pd

base_df = pd.read_csv('Copie de ORGANISME DE FORMATION.csv', dtype=str).fillna("")
dgefp_df = pd.read_csv('listes DGFP.csv', dtype=str).fillna("")

base_df.columns = base_df.columns.str.strip()
dgefp_df.columns = dgefp_df.columns.str.strip()

entreprises_base = base_df[~base_df['SIRET'].isin(dgefp_df['siretetablissementdeclarant'])].fillna("")

entreprises_base.to_csv('entreprises_de_yav_qui_sont_plus_dans_DGEFP.csv', index=False)

print(f"\033[1;31mNombre total: {len(entreprises_base)}\033[0m")

entreprises_base

Nombre total: 29276

,NOM.,Unnamed: 1,ADRESSE,CODE POSTAL,VILLE,TELEPHONE,ADRESSE E-MAIL,FORME_JURIDIQUE,DIRIGEANT,IMMATRICULATION,ANNEE_CA,CA,RESULTAT,EFFECTIF,NAF APE,SIRET,EFFECTIF_MIN,EFFECTIF_MAX,Qualiopi ?
0,301,,801 AVENUE CHAMPS BLANCS,35510,CESSON SEVIGNE,02 44 10 13 50,contact@formaouest.fr,Societe par actions simplifiee a associe unique,MVGROUP (personne morale),8 septembre 1999,2019,28 605 140 €,344 763 €,,6311Z,42417608900102,,,Oui
1,981,,129 AVENUE GENEVE,74000,ANNECY,06 08 75 22 43,nicolas@pluceo.fr,Société à responsabilité limitée à associé unique,BOUVIER FRANCOIS,23 mars 2009,2021,,,,8559A,51117706500022,,,Oui
2,'PISTE SECURITE',,41 RUE MOLIERE,92120,MONTROUGE,06 60 11 81 90,contact@piste-securite.com,,ALI DAMIR,,,,,,7490B,82853477600020,,,Oui
3,'PISTE SECURITE',,41 RUE MOLIERE,92120,MONTROUGE,06 60 11 81 90,damir.ali@piste-securite.com,,,,,,,,,,,,Oui
4,& CO,,67 RUE EOLE,14370,CHICHEBOVILLE,02 31 23 30 00,ouine@wanadoo.fr,,,,,,,,,,,,Oui
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38679,ZORBA FORMATION CONCEPT,,7 SQUARE JULES VERNE,56890,ST AVE,06 30 64 14 09,f.dubreuil.epgv@gmail.com,,,,,,,,,,,,Oui
38680,ZORBA FORMATION CONCEPT,,7 SQUARE JULES VERNE,56890,ST AVE,06 30 64 14 09,pierre.cougoulic@wanadoo.fr,,,,,,,,,,,,Oui
38681,ZUILI A,,147 AVENUE MONT VENTOUX,84450,JONQUERETTES,04 90 85 09 17,anais.zuili@sophrologie-relationnelle.fr,,,,,,,,8559B,32944822900057,1,2,Oui
38683,ZULLO JOSE,,9 RUE VAVIN,75006,PARIS,06 88 62 49 42,concrescoconseil@gmail.com,,,,,,,,8560Z,40162302000039,,,Oui
38684,ZULLO JOSE,,9 RUE VAVIN,75006,PARIS,06 88 62 49 42,jzullo@solocal.com,,,,,,,,8560Z,40162302000039,,,Oui

<span style="color: white; font-weight: bold; font-size: 50px;">Ceux qui existent dans Base & dans DGEFP - et qui sont Certifiées Qualiopi</span>

In [16]:
import pandas as pd

base_df = pd.read_csv('Copie de ORGANISME DE FORMATION.csv', dtype=str).fillna("")
dgefp_df = pd.read_csv('listes DGFP.csv', dtype=str).fillna("")

base_df.columns = base_df.columns.str.strip()
dgefp_df.columns = dgefp_df.columns.str.strip()

colonnes_qualiopi = [
    'certifications_actionsdeformation',
    'certifications_bilansdecompetences',
    'certifications_vae',
]

colonnes_finales = [
    'NOM', 'Unnamed: 1', 'ADRESSE', 'CODE POSTAL', 'VILLE', 'TELEPHONE', 'ADRESSE E-MAIL',
    'FORME_JURIDIQUE', 'DIRIGEANT', 'IMMATRICULATION', 'ANNEE_CA', 'CA', 'RESULTAT',
    'EFFECTIF', 'NAF APE', 'SIRET', 'EFFECTIF_MIN', 'EFFECTIF_MAX', 'Qualiopi ?'
] + colonnes_qualiopi

entreprises_communes = base_df[base_df['SIRET'].isin(dgefp_df['siretetablissementdeclarant'])].copy()

dgefp_unique = dgefp_df.drop_duplicates(subset=['siretetablissementdeclarant'])[["siretetablissementdeclarant"] + colonnes_qualiopi]

entreprises_communes = entreprises_communes.merge(
    dgefp_unique,
    left_on="SIRET",
    right_on="siretetablissementdeclarant",
    how="left"
).drop(columns=["siretetablissementdeclarant"], errors="ignore")

colonnes_existantes = [col for col in colonnes_finales if col in entreprises_communes.columns]
entreprises_communes = entreprises_communes[colonnes_existantes]

for col in colonnes_qualiopi:
    entreprises_communes[col] = entreprises_communes[col].apply(lambda x: True if x.strip() else False)

entreprises_communes.to_csv('entreprises_presentes_dans_les_deux.csv', index=False)

print(f"\033[1;31mNombre total: {len(entreprises_communes)}\033[0m")

entreprises_communes

Nombre total: 9409

,Unnamed: 1,ADRESSE,CODE POSTAL,VILLE,TELEPHONE,ADRESSE E-MAIL,FORME_JURIDIQUE,DIRIGEANT,IMMATRICULATION,ANNEE_CA,...,RESULTAT,EFFECTIF,NAF APE,SIRET,EFFECTIF_MIN,EFFECTIF_MAX,Qualiopi ?,certifications_actionsdeformation,certifications_bilansdecompetences,certifications_vae
0,,10 BOULEVARD RALLI,13008,MARSEILLE,04 13 25 88 95,contact@1mainformation.com,,BEN-JAMIN PHILIPPE,,,...,,,8559A,91473931300015,,,Oui,True,True,True
1,,CHEMIN MOULIN NEUF,04100,MANOSQUE,04 92 75 01 77,admin@100pcenglish.com,Société à responsabilité limitée,GLIDEWELL PENELOPE,6 décembre 2007,2021,...,-43 847 €,,8559A,49940161000021,3,5,Oui,True,True,True
2,,190 RUE 19 MARS 1962,30200,BAGNOLS SUR CEZE,09 81 26 93 91,b.lombart@1630formation.fr,Société à responsabilité limitée,HONORIN JEAN-BAPTISTE,25 février 2011,2021,...,,,8559A,53060076600022,6,9,Oui,True,True,True
3,,190 RUE 19 MARS 1962,30200,BAGNOLS SUR CEZE,09 81 26 93 91,contact@1630formation.fr,Société à responsabilité limitée,HONORIN JEAN-BAPTISTE,25 février 2011,2021,...,,,8559A,53060076600022,6,9,Oui,True,True,True
4,,RUE 19 MARS 1962,30200,BAGNOLS SUR CEZE,09 81 26 93 91,jb.honorin@1630formation.fr,Société à responsabilité limitée,HONORIN JEAN-BAPTISTE,25 février 2011,2021,...,,,8559A,53060076600022,6,9,Oui,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9404,,32 RUE PARADIS,75010,PARIS,01 44 61 96 00,p.girard@ziggourat.com,Société à responsabilité limitée,EPIFANIE AXEL,10 février 1997,2022,...,,,8559A,41087543900045,10,19,Oui,True,True,True
9405,,72 ROUTE TREHUINEC,56000,VANNES,02 97 63 62 59,nadine.lemeut@zixinecompetences.fr,,OGOR NADINE,,,...,,,8559A,79337909000012,,,Oui,True,True,True
9406,,18 RUE TOURTILLE,75020,PARIS,01 84 17 82 56,contact@zoomup.biz,,NORSIC STEPHAN,,,...,,,9329Z,44939145700065,,,Oui,False,False,False
9407,,18 RUE TOURTILLE,75020,PARIS,01 84 17 82 56,contact@zoomup.fr,,,,,...,,,9329Z,44939145700065,,,Oui,False,False,False
9408,,147 AVENUE MONT VENTOUX,84450,JONQUERETTES,04 90 85 09 17,anais@sophrozuili.com,Societe par actions simplifiee,,26 juillet 2016,2020,...,,,8559A,82167328200017,,,Oui,True,True,True

<span style="color: white; font-weight: bold; font-size: 50px;">Ceux qui existent dans Base & dans DGEFP - et qui sont Non Certifiées Qualiopi</span>

In [17]:
import pandas as pd

base_df = pd.read_csv('Copie de ORGANISME DE FORMATION.csv', dtype=str).fillna("")
dgefp_df = pd.read_csv('listes DGFP.csv', dtype=str).fillna("")

base_df.columns = base_df.columns.str.strip()
dgefp_df.columns = dgefp_df.columns.str.strip()

colonnes_qualiopi = [
    'certifications_actionsdeformation',
    'certifications_bilansdecompetences',
    'certifications_vae',
]

colonnes_finales = [
    'NOM', 'Unnamed: 1', 'ADRESSE', 'CODE POSTAL', 'VILLE', 'TELEPHONE', 'ADRESSE E-MAIL',
    'FORME_JURIDIQUE', 'DIRIGEANT', 'IMMATRICULATION', 'ANNEE_CA', 'CA', 'RESULTAT',
    'EFFECTIF', 'NAF APE', 'SIRET', 'EFFECTIF_MIN', 'EFFECTIF_MAX', 'Qualiopi ?'
] + colonnes_qualiopi

entreprises_communes = base_df[base_df['SIRET'].isin(dgefp_df['siretetablissementdeclarant'])].copy()

dgefp_unique = dgefp_df.drop_duplicates(subset=['siretetablissementdeclarant'])[["siretetablissementdeclarant"] + colonnes_qualiopi]

entreprises_communes = entreprises_communes.merge(
    dgefp_unique,
    left_on="SIRET",
    right_on="siretetablissementdeclarant",
    how="left"
).drop(columns=["siretetablissementdeclarant"], errors="ignore")

entreprises_communes = entreprises_communes.fillna("")

colonnes_existantes = [col for col in colonnes_finales if col in entreprises_communes.columns]
entreprises_communes = entreprises_communes[colonnes_existantes]

entreprises_non_certifiees = entreprises_communes[
    (entreprises_communes['certifications_actionsdeformation'] == "") &
    (entreprises_communes['certifications_bilansdecompetences'] == "") &
    (entreprises_communes['certifications_vae'] == "")
]

entreprises_non_certifiees.to_csv('entreprises_non_certifiees_qualiopi.csv', index=False)

print(f"\033[1;31mNombre total: {len(entreprises_non_certifiees)}\033[0m")

entreprises_non_certifiees

Nombre total: 2165

,Unnamed: 1,ADRESSE,CODE POSTAL,VILLE,TELEPHONE,ADRESSE E-MAIL,FORME_JURIDIQUE,DIRIGEANT,IMMATRICULATION,ANNEE_CA,...,RESULTAT,EFFECTIF,NAF APE,SIRET,EFFECTIF_MIN,EFFECTIF_MAX,Qualiopi ?,certifications_actionsdeformation,certifications_bilansdecompetences,certifications_vae
7,,109 AVENUE LESPINET,31400,TOULOUSE,06 83 24 73 01,alain.caujolle@1a2performance.fr,,CAUJOLLE ALAIN,,,...,,,8559A,79769288600022,,,Oui,,,
8,,109 AVENUE LESPINET,31400,TOULOUSE,06 83 24 73 01,contact@1a2performance.fr,,CAUJOLLE ALAIN,,,...,,,8559A,79769288600022,,,Oui,,,
16,,7 RUE VIADUC PERS,15290,ROUGET PERS (LE),04 71 64 77 31,contact@2dcoprev.fr,Société par actions simplifiée à associé unique,DUBOIS DIDIER,15 décembre 2017,2021,...,,,7022Z,83400936700014,,,Non,,,
19,,20 AVENUE PONT ROYAL,94230,CACHAN,06 04 18 56 94,acvn.cachan@orange.fr,,,,,...,,,4619B,52796481100014,,,Non,,,
20,,20 AVENUE PONT ROYAL,94230,CACHAN,06 04 18 56 94,philippe.petit@2pconseil.net,,PETIT PHILIPPE,,,...,,,4619B,52796481100014,,,Non,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9391,,18 AVENUE TEISSEIRE,38100,GRENOBLE,06 87 24 04 22,christine.zambelli@oseki.fr,,ZAMBELLI CHRISTINE,,,...,,,8559A,48422984400028,,,Non,,,
9395,,2 ALLEE CANCHE,31770,COLOMIERS,06 28 08 95 40,contact@zenathitude.fr,,METAS NATHALIE,,,...,,,9602B,52909130800013,,,Non,,,
9396,,2 ALLEE CANCHE,31770,COLOMIERS,06 28 08 95 40,zenathitude@gmail.com,,METAS NATHALIE,,,...,,,9602B,52909130800013,,,Non,,,
9406,,18 RUE TOURTILLE,75020,PARIS,01 84 17 82 56,contact@zoomup.biz,,NORSIC STEPHAN,,,...,,,9329Z,44939145700065,,,Oui,,,
9407,,18 RUE TOURTILLE,75020,PARIS,01 84 17 82 56,contact@zoomup.fr,,,,,...,,,9329Z,44939145700065,,,Oui,,,

<span style="color: white; font-weight: bold; font-size: 50px;">Ceux qui existent dans YAV & dans Base-email</span>

In [19]:
import pandas as pd

base_df = pd.read_csv('Copie de ORGANISME DE FORMATION.csv', dtype=str).fillna("")
dgefp_df = pd.read_csv('listes DGFP.csv', dtype=str).fillna("")

base_df.columns = base_df.columns.str.strip()
dgefp_df.columns = dgefp_df.columns.str.strip()

colonnes_qualiopi = [
    'certifications_actionsdeformation',
    'certifications_bilansdecompetences',
    'certifications_vae',
]

colonnes_finales = [
    'NOM', 'Unnamed: 1', 'ADRESSE', 'CODE POSTAL', 'VILLE', 'TELEPHONE', 'ADRESSE E-MAIL',
    'FORME_JURIDIQUE', 'DIRIGEANT', 'IMMATRICULATION', 'ANNEE_CA', 'CA', 'RESULTAT',
    'EFFECTIF', 'NAF APE', 'SIRET', 'EFFECTIF_MIN', 'EFFECTIF_MAX', 'Qualiopi ?'
] + colonnes_qualiopi

entreprises_communes = base_df[base_df['SIRET'].isin(dgefp_df['siretetablissementdeclarant'])].copy()

dgefp_unique = dgefp_df.drop_duplicates(subset=['siretetablissementdeclarant'])[["siretetablissementdeclarant"] + colonnes_qualiopi]

entreprises_communes = entreprises_communes.merge(
    dgefp_unique,
    left_on="SIRET",
    right_on="siretetablissementdeclarant",
    how="left"
).drop(columns=["siretetablissementdeclarant"], errors="ignore")

entreprises_communes = entreprises_communes.fillna("")

colonnes_existantes = [col for col in colonnes_finales if col in entreprises_communes.columns]
entreprises_communes = entreprises_communes[colonnes_existantes]

entreprises_non_certifiees = entreprises_communes[
    (entreprises_communes['certifications_actionsdeformation'] == "") &
    (entreprises_communes['certifications_bilansdecompetences'] == "") &
    (entreprises_communes['certifications_vae'] == "")
]

entreprises_non_certifiees.to_csv('entreprises_non_certifiees_qualiopi.csv', index=False)

print(f"\033[1;31mNombre total: {len(entreprises_non_certifiees)}\033[0m")

entreprises_non_certifiees

Nombre total: 2165

,Unnamed: 1,ADRESSE,CODE POSTAL,VILLE,TELEPHONE,ADRESSE E-MAIL,FORME_JURIDIQUE,DIRIGEANT,IMMATRICULATION,ANNEE_CA,...,RESULTAT,EFFECTIF,NAF APE,SIRET,EFFECTIF_MIN,EFFECTIF_MAX,Qualiopi ?,certifications_actionsdeformation,certifications_bilansdecompetences,certifications_vae
7,,109 AVENUE LESPINET,31400,TOULOUSE,06 83 24 73 01,alain.caujolle@1a2performance.fr,,CAUJOLLE ALAIN,,,...,,,8559A,79769288600022,,,Oui,,,
8,,109 AVENUE LESPINET,31400,TOULOUSE,06 83 24 73 01,contact@1a2performance.fr,,CAUJOLLE ALAIN,,,...,,,8559A,79769288600022,,,Oui,,,
16,,7 RUE VIADUC PERS,15290,ROUGET PERS (LE),04 71 64 77 31,contact@2dcoprev.fr,Société par actions simplifiée à associé unique,DUBOIS DIDIER,15 décembre 2017,2021,...,,,7022Z,83400936700014,,,Non,,,
19,,20 AVENUE PONT ROYAL,94230,CACHAN,06 04 18 56 94,acvn.cachan@orange.fr,,,,,...,,,4619B,52796481100014,,,Non,,,
20,,20 AVENUE PONT ROYAL,94230,CACHAN,06 04 18 56 94,philippe.petit@2pconseil.net,,PETIT PHILIPPE,,,...,,,4619B,52796481100014,,,Non,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9391,,18 AVENUE TEISSEIRE,38100,GRENOBLE,06 87 24 04 22,christine.zambelli@oseki.fr,,ZAMBELLI CHRISTINE,,,...,,,8559A,48422984400028,,,Non,,,
9395,,2 ALLEE CANCHE,31770,COLOMIERS,06 28 08 95 40,contact@zenathitude.fr,,METAS NATHALIE,,,...,,,9602B,52909130800013,,,Non,,,
9396,,2 ALLEE CANCHE,31770,COLOMIERS,06 28 08 95 40,zenathitude@gmail.com,,METAS NATHALIE,,,...,,,9602B,52909130800013,,,Non,,,
9406,,18 RUE TOURTILLE,75020,PARIS,01 84 17 82 56,contact@zoomup.biz,,NORSIC STEPHAN,,,...,,,9329Z,44939145700065,,,Oui,,,
9407,,18 RUE TOURTILLE,75020,PARIS,01 84 17 82 56,contact@zoomup.fr,,,,,...,,,9329Z,44939145700065,,,Oui,,,

In [23]:
import pandas as pd

yav_df = pd.read_csv('companyyavlist.csv', dtype=str).fillna("")
dgefp_df = pd.read_csv('ORGANISME_DE_FORMATION_CLEAN.csv', dtype=str).fillna("")

yav_df.columns = yav_df.columns.str.strip()
dgefp_df.columns = dgefp_df.columns.str.strip()

if 'Siret' in yav_df.columns and 'SIRET' in dgefp_df.columns:
    yav_df = yav_df.rename(columns={'Siret': 'SIRET'})

yav_df['SIRET'] = yav_df['SIRET'].str.strip()
dgefp_df['SIRET'] = dgefp_df['SIRET'].str.strip()

entreprises_communes = yav_df.merge(dgefp_df, on="SIRET", how="inner")

entreprises_communes = entreprises_communes.drop_duplicates()

entreprises_communes.to_csv('entreprises_com.csv', index=False)

print(f"\033[1;31mNombre total: {len(entreprises_communes)}\033[0m")

entreprises_communes

Nombre total: 34251

,ID,CompanyId,nom,Email,Crée,Mobile,Phones,Activite1,Activite2,Activite3,...,DIRIGEANT,IMMATRICULATION,ANNEE_CA,CA,RESULTAT,EFFECTIF,NAF APE,EFFECTIF_MIN,EFFECTIF_MAX,Qualiopi ?
0,220,220,2D.COPREV,,2023-06-09T10:32:26+03:00,,,,,,...,DUBOIS DIDIER,15 décembre 2017,2021.0,,,,7022Z,,,Non
1,458,458,3 I PROJECT FORMATION,,2023-06-09T10:32:34+03:00,,,"Informatique, traitement de l'information, rés...",,,...,ZOCCOLI JEAN-FRANCOIS,8 septembre 2006,2021.0,,,,8559A,,,Non
2,482,482,3PA - MACONDO,,2023-06-09T10:32:35+03:00,,,Spécialités plurivalentes de l'agronomie et de...,"Productions végétales,cultures spécialisées","Energie, génie climatique",...,3PA - MACONDO,,,,,,9499Z,,,Non
3,656,656,A2C FORMATIONS,boutonnatp@gmail.com,2023-06-09T10:32:41+03:00,06 61 74 87 41,06 61 74 87 41,Autres...,,,...,A2C FORMATIONS,,,,,,8559A,,,Oui
4,720,720,A3CGP,cedric.avrillaud@gmail.com,2023-06-09T10:32:43+03:00,06 64 17 77 49,06 64 17 77 49,"Finances, banque, assurances",,,...,AVRILLAUD CEDRIC,27 septembre 2016,2021.0,,,,6831Z,,,Oui
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34246,501938,501938,MERCATES CONSULTING,,2025-03-11T18:01:38+03:00,,,"Ressources humaines, gestion du personnel, ges...",,,...,,19 juin 2003,2021.0,41 591 €,11 765 €,,8559A,,,Oui
34247,502196,502196,Monsieur GIUSEPPE CONTI,,2025-03-11T18:13:35+03:00,,,Développement des capacités comportementales e...,,,...,CONTI GIUSEPPE,,,,,,8559B,,,Oui
34248,503212,503212,SOHENA,,2025-03-12T15:34:51+03:00,,,Santé,,,...,DRAUSSIN THIERRY,3 juin 2020,2021.0,,,,7022,,,Oui
34249,503264,503264,TEAM CONCEPT,,2025-03-12T15:34:56+03:00,,,Développement des capacités mentales et appren...,,,...,PICAVET SYLVIE,,,,,,7022Z,,,Oui
34250,503324,503324,URSZULA DYRBUSZ,,2025-03-12T15:42:40+03:00,,,"Langues vivantes, civilisations étrangères et ...",,,...,DYRBUSZ URSZULA,,,,,,8559A,,,Oui

<span style="color: white; font-weight: bold; font-size: 50px;">Ajout des valeurs de la colonne TELEPHONE-Base-email vers Phones-YAV si vide</span>

In [32]:
import pandas as pd

df = pd.read_csv('entreprises_com.csv', dtype=str).fillna("")

if 'TELEPHONE' in df.columns and 'Phones' in df.columns:

    df['Phones'] = df['Phones'].mask(df['Phones'] == "", df['TELEPHONE'])

df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

df = df.drop_duplicates(subset=['SIRET'])

df.to_csv('entreprises_comgdt.csv', index=False)

print("\033[1;32mMise à jour terminée : valeurs copiées de TELEPHONE-Base-email vers Phones-YAV si vide.\033[0m")

df

Mise à jour terminée : valeurs copiées de TELEPHONE-Base-email vers Phones-YAV si vide.

,ID,CompanyId,nom,Email,Crée,Mobile,Phones,Activite1,Activite2,Activite3,...,DIRIGEANT,IMMATRICULATION,ANNEE_CA,CA,RESULTAT,EFFECTIF,NAF APE,EFFECTIF_MIN,EFFECTIF_MAX,Qualiopi ?
0,220,220,2D.COPREV,,2023-06-09T10:32:26+03:00,,04 71 64 77 31,,,,...,DUBOIS DIDIER,15 décembre 2017,2021.0,,,,7022Z,,,Non
1,458,458,3 I PROJECT FORMATION,,2023-06-09T10:32:34+03:00,,04 72 57 98 08,"Informatique, traitement de l'information, rés...",,,...,ZOCCOLI JEAN-FRANCOIS,8 septembre 2006,2021.0,,,,8559A,,,Non
2,482,482,3PA - MACONDO,,2023-06-09T10:32:35+03:00,,06 38 30 68 04,Spécialités plurivalentes de l'agronomie et de...,"Productions végétales,cultures spécialisées","Energie, génie climatique",...,3PA - MACONDO,,,,,,9499Z,,,Non
3,656,656,A2C FORMATIONS,boutonnatp@gmail.com,2023-06-09T10:32:41+03:00,06 61 74 87 41,06 61 74 87 41,Autres...,,,...,A2C FORMATIONS,,,,,,8559A,,,Oui
4,720,720,A3CGP,cedric.avrillaud@gmail.com,2023-06-09T10:32:43+03:00,06 64 17 77 49,06 64 17 77 49,"Finances, banque, assurances",,,...,AVRILLAUD CEDRIC,27 septembre 2016,2021.0,,,,6831Z,,,Oui
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34246,501938,501938,MERCATES CONSULTING,,2025-03-11T18:01:38+03:00,,03 20 89 35 25,"Ressources humaines, gestion du personnel, ges...",,,...,,19 juin 2003,2021.0,41 591 €,11 765 €,,8559A,,,Oui
34247,502196,502196,Monsieur GIUSEPPE CONTI,,2025-03-11T18:13:35+03:00,,06 19 62 26 68,Développement des capacités comportementales e...,,,...,CONTI GIUSEPPE,,,,,,8559B,,,Oui
34248,503212,503212,SOHENA,,2025-03-12T15:34:51+03:00,,06 14 26 18 42,Santé,,,...,DRAUSSIN THIERRY,3 juin 2020,2021.0,,,,7022,,,Oui
34249,503264,503264,TEAM CONCEPT,,2025-03-12T15:34:56+03:00,,06 35 31 02 13,Développement des capacités mentales et appren...,,,...,PICAVET SYLVIE,,,,,,7022Z,,,Oui
34250,503324,503324,URSZULA DYRBUSZ,,2025-03-12T15:42:40+03:00,,03 88 32 05 70,"Langues vivantes, civilisations étrangères et ...",,,...,DYRBUSZ URSZULA,,,,,,8559A,,,Oui

In [33]:
import pandas as pd
import requests
import configparser
import time
import logging

logging.basicConfig(filename="bitrix_update.log", level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
console = logging.StreamHandler()
console.setLevel(logging.INFO)
logging.getLogger("").addHandler(console)

logging.info("Démarrage du script")

config = configparser.ConfigParser()
config.read('config.ini')

BITRIX_DOMAIN = config.get('BITRIX', 'BITRIX_DOMAIN')
BITRIX_TOKEN = config.get('BITRIX', 'BITRIX_TOKEN')

if not BITRIX_DOMAIN or not BITRIX_TOKEN:
    logging.error("Domaine et/ou token Bitrix manquants dans config.ini")
    raise ValueError("Domaine et/ou token Bitrix manquants dans config.ini")

csv_file = "entreprises_comgdt.csv"
df_csv = pd.read_csv(csv_file, dtype=str).fillna("")
logging.info(f"CSV chargé : {len(df_csv)} lignes.")

def get_existing_ids_from_bitrix():
    bitrix_url = f"https://{BITRIX_DOMAIN}/rest/1/{BITRIX_TOKEN}/crm.company.list.json"
    params = {"select[]": "ID"}
    existing_ids = set()
    start = 0
    max_retries = 5

    logging.info("Récupération des ID depuis Bitrix...")

    while True:
        for attempt in range(max_retries):
            try:
                response = requests.get(bitrix_url, params={**params, "start": start})
                response.raise_for_status()
                data = response.json()
                break
            except requests.exceptions.RequestException as e:
                wait_time = 10 * (attempt + 1)
                logging.warning(f"Erreur {e}. Nouvelle tentative dans {wait_time} secondes...")
                time.sleep(wait_time)
        else:
            logging.error("Échec après plusieurs tentatives.")
            return existing_ids

        if "result" in data:
            for company in data["result"]:
                existing_ids.add(company["ID"])
        if "next" in data:
            start = data["next"]
        else:
            break

    logging.info(f"{len(existing_ids)} entreprises récupérées de Bitrix.")
    return existing_ids

existing_ids_bitrix = get_existing_ids_from_bitrix()

df_csv_filtered = df_csv[df_csv["ID"].isin(existing_ids_bitrix)]

if df_csv_filtered.empty:
    logging.info("Aucune entreprise du CSV ne correspond à un ID existant dans Bitrix. Fin du script.")
else:
    logging.info(f"{len(df_csv_filtered)} entreprises à mettre à jour.")

    update_url = f"https://{BITRIX_DOMAIN}/rest/1/{BITRIX_TOKEN}/crm.company.update.json"

    max_requests = 300
    pause_duration = 100
    max_retries = 5

    for index, row in df_csv_filtered.iterrows():
        company_id = row["ID"]
       
        uf_value = row["Phones"]

        params = {
            "id": company_id,
            "fields[UF_CRM_1741080141]": uf_value
        }

        for attempt in range(max_retries):
            try:
                response = requests.post(update_url, params=params)
                response.raise_for_status()
                result = response.json()

                if "error" in result:
                    logging.warning(f"rreur pour ID {company_id} : {result['error_description']}")
                else:
                    logging.info(f"ID {company_id} mis à jour avec succès.")
                break
            except requests.exceptions.RequestException as e:
                wait_time = 10 * (attempt + 1)
                logging.warning(f"Erreur réseau pour ID {company_id} : {e}. Nouvelle tentative dans {wait_time} secondes...")
                time.sleep(wait_time)
        else:
            logging.error(f"Échec après {max_retries} tentatives pour ID {company_id}.")

        if (index + 1) % max_requests == 0:
            logging.info(f"Pause de {pause_duration} secondes pour éviter le rate limit...")
            time.sleep(pause_duration)

    logging.info("Mise à jour des entreprises terminée.")

Démarrage du script
Démarrage du script
CSV chargé : 1585 lignes.
CSV chargé : 1585 lignes.
Récupération des ID depuis Bitrix...
Récupération des ID depuis Bitrix...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=7150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=7150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=8750. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=8750. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=10150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=10150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=11600. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=11600. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=13050. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=13050. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=14500. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=14500. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=16150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=16150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=17750. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=17750. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=19150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=19150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=20900. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=20900. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=22350. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=22350. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=23850. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=23850. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=25250. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=25250. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=26750. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=26750. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=28200. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=28200. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=29850. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=29850. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=31350. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=31350. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=32900. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=32900. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=34450. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=34450. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=36000. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=36000. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=37600. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=37600. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=39050. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=39050. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=40500. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=40500. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=42050. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=42050. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=43450. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=43450. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=44900. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=44900. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=46400. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=46400. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=47900. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=47900. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=49400. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=49400. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=50900. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=50900. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=52300. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=52300. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=53950. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=53950. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=55500. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=55500. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=57150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=57150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=58650. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=58650. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=60100. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=60100. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=61550. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=61550. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=63150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=63150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=64650. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=64650. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=66300. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=66300. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=67750. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=67750. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=69250. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=69250. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=70650. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=70650. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=72200. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=72200. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=73700. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=73700. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=75150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=75150. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=76700. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=76700. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=78400. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=78400. Nouvelle tentative dans 10 secondes...
Erreur 503 Server Error: Service Temporarily Unavailable for url: https://yav.bitrix24.fr/rest/1/r6iblclq1i8nldu6/crm.company.list.json?select%5B%5D=ID&start=79900. Nouvelle tentative dans 10 secondes...